// ============================================================================
// NATURAL LANGUAGE SEARCH
// DawinOS v2.0 - Intelligence Layer
// Search bar for natural language queries across all modules
// ============================================================================

import React, { useState, useRef } from 'react';
import {
  Sparkles,
  History,
  Lightbulb,
  X,
  Send,
  Loader2,
} from 'lucide-react';

import { Card, CardContent } from '@/core/components/ui/card';
import { Button } from '@/core/components/ui/button';
import { Input } from '@/core/components/ui/input';
import { Badge } from '@/core/components/ui/badge';

import { MODULE_COLOR } from '../../constants';
import type { NLQueryResponse } from '../../types';

interface NaturalLanguageSearchProps {
  onQuery?: (query: string) => Promise<NLQueryResponse>;
  recentQueries?: string[];
  suggestedQueries?: string[];
  placeholder?: string;
}

export const NaturalLanguageSearch: React.FC<NaturalLanguageSearchProps> = ({
  onQuery,
  recentQueries = [],
  suggestedQueries = [],
  placeholder = 'Ask anything about your business data...',
}) => {
  const [query, setQuery] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [response, setResponse] = useState<NLQueryResponse | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const defaultSuggestedQueries = suggestedQueries.length > 0 ? suggestedQueries : [
    'What was our revenue last month?',
    'Show me employee performance trends',
    'Which deals are closing this quarter?',
    'Summarize recent competitor activity',
    'What are the pending approvals?',
  ];

  const handleSubmit = async () => {
    if (!query.trim() || isProcessing) return;

    setIsProcessing(true);
    setShowSuggestions(false);

    try {
      if (onQuery) {
        const result = await onQuery(query.trim());
        setResponse(result);
      } else {
        // Mock response
        await new Promise(resolve => setTimeout(resolve, 1500));
        setResponse({
          type: 'summary',
          content: `Based on your query "${query}", I found relevant data across multiple modules.`,
          explanation: 'This response was generated by analyzing data from Financial Hub and HR Central.',
          confidence: 0.85,
          suggestedFollowUps: [
            'Show me more details',
            'Compare with last month',
            'Export this data',
          ],
        });
      }
    } catch (error) {
      setResponse({
        type: 'error',
        content: 'Sorry, I encountered an error processing your query.',
        explanation: 'Please try rephrasing your question.',
        confidence: 0,
      });
    }

    setIsProcessing(false);
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setQuery(suggestion);
    setShowSuggestions(false);
    inputRef.current?.focus();
  };

  const handleClear = () => {
    setQuery('');
    setResponse(null);
    inputRef.current?.focus();
  };

  return (
    <div className="relative">
      {/* Search Input */}
      <div
        className="flex items-center gap-2 p-1 rounded-xl border-2 bg-background shadow-sm transition-colors"
        style={{ borderColor: showSuggestions ? MODULE_COLOR : 'transparent' }}
      >
        <div className="pl-3">
          {isProcessing ? (
            <Loader2 className="h-5 w-5 animate-spin" style={{ color: MODULE_COLOR }} />
          ) : (
            <Sparkles className="h-5 w-5" style={{ color: MODULE_COLOR }} />
          )}
        </div>

        <Input
          ref={inputRef}
          placeholder={placeholder}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onFocus={() => setShowSuggestions(true)}
          onBlur={() => setTimeout(() => setShowSuggestions(false), 200)}
          onKeyPress={handleKeyPress}
          className="flex-1 border-0 shadow-none focus-visible:ring-0"
        />

        {query && (
          <Button variant="ghost" size="icon" onClick={handleClear}>
            <X className="h-4 w-4" />
          </Button>
        )}

        <Button
          onClick={handleSubmit}
          disabled={!query.trim() || isProcessing}
          className="mr-1"
          style={{ backgroundColor: MODULE_COLOR }}
        >
          <Send className="h-4 w-4" />
        </Button>
      </div>

      {/* Suggestions Dropdown */}
      {showSuggestions && !isProcessing && !response && (
        <Card className="absolute top-full left-0 right-0 mt-2 z-50 shadow-lg">
          <CardContent className="p-0">
            {/* Recent Queries */}
            {recentQueries.length > 0 && (
              <>
                <div className="px-4 py-2 bg-muted/50">
                  <p className="text-xs font-medium text-muted-foreground">Recent Queries</p>
                </div>
                <div className="py-1">
                  {recentQueries.slice(0, 3).map((q, idx) => (
                    <button
                      key={idx}
                      className="w-full flex items-center gap-3 px-4 py-2 hover:bg-muted text-left"
                      onClick={() => handleSuggestionClick(q)}
                    >
                      <History className="h-4 w-4 text-muted-foreground" />
                      <span className="text-sm">{q}</span>
                    </button>
                  ))}
                </div>
                <div className="border-t" />
              </>
            )}

            {/* Suggested Queries */}
            <div className="px-4 py-2 bg-muted/50">
              <p className="text-xs font-medium text-muted-foreground">Try asking</p>
            </div>
            <div className="py-1">
              {defaultSuggestedQueries.map((q, idx) => (
                <button
                  key={idx}
                  className="w-full flex items-center gap-3 px-4 py-2 hover:bg-muted text-left"
                  onClick={() => handleSuggestionClick(q)}
                >
                  <Lightbulb className="h-4 w-4" style={{ color: MODULE_COLOR }} />
                  <span className="text-sm">{q}</span>
                </button>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Response Display */}
      {response && (
        <Card className="mt-4">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <Sparkles className="h-5 w-5 shrink-0 mt-0.5" style={{ color: MODULE_COLOR }} />
              <div className="flex-1">
                <p className="mb-2">{response.content}</p>

                {response.explanation && (
                  <p className="text-sm text-muted-foreground mb-3">
                    {response.explanation}
                  </p>
                )}

                <div className="flex items-center gap-2 mb-3">
                  <Badge
                    className={response.confidence > 0.7 ? 'bg-green-500' : 'bg-yellow-500'}
                  >
                    {Math.round(response.confidence * 100)}% confidence
                  </Badge>
                  <Badge variant="outline">{response.type}</Badge>
                </div>

                {response.suggestedFollowUps && response.suggestedFollowUps.length > 0 && (
                  <div>
                    <p className="text-xs text-muted-foreground mb-2">Follow-up questions:</p>
                    <div className="flex flex-wrap gap-2">
                      {response.suggestedFollowUps.map((followUp, idx) => (
                        <Badge
                          key={idx}
                          variant="outline"
                          className="cursor-pointer hover:bg-muted"
                          onClick={() => handleSuggestionClick(followUp)}
                        >
                          {followUp}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              <Button variant="ghost" size="icon" onClick={() => setResponse(null)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default NaturalLanguageSearch;
