// ============================================================================
// ENVIRONMENT SCANNING MODULE INDEX
// DawinOS v2.0 - Market Intelligence Module
// Export all environment scanning functionality
// ============================================================================

// Constants
export {
  PESTEL_DIMENSIONS,
  PESTEL_DIMENSION_CONFIG,
  IMPACT_LEVELS,
  IMPACT_LEVEL_CONFIG,
  PROBABILITY_LEVELS,
  PROBABILITY_LEVEL_CONFIG,
  SIGNAL_TYPES,
  SIGNAL_TYPE_CONFIG,
  SIGNAL_SOURCES,
  SIGNAL_SOURCE_CONFIG,
  SIGNAL_STATUSES,
  SIGNAL_STATUS_CONFIG,
  REGULATORY_CATEGORIES,
  REGULATORY_CATEGORY_CONFIG,
  REGULATORY_STATUSES,
  REGULATORY_STATUS_CONFIG,
  COMPLIANCE_STATUSES,
  COMPLIANCE_STATUS_CONFIG,
  SCENARIO_TYPES,
  SCENARIO_TYPE_CONFIG,
  TIME_HORIZONS,
  TIME_HORIZON_CONFIG,
  ALERT_PRIORITIES,
  ALERT_PRIORITY_CONFIG,
  TRIGGER_CONDITIONS,
  TRIGGER_CONDITION_CONFIG,
  UGANDA_ECONOMIC_INDICATORS,
  UGANDA_ECONOMIC_INDICATOR_CONFIG,
  AFFECTED_BUSINESS_AREAS,
  AFFECTED_BUSINESS_AREA_LABELS,
  SCANNING_COLLECTIONS,
} from './constants/scanning.constants';

export type {
  PESTELDimension,
  ImpactLevel,
  ProbabilityLevel,
  SignalType,
  SignalSource,
  SignalStatus,
  RegulatoryCategory,
  RegulatoryStatus,
  ComplianceStatus,
  ScenarioType,
  TimeHorizon,
  AlertPriority,
  TriggerCondition,
  UgandaEconomicIndicator,
  AffectedBusinessArea,
} from './constants/scanning.constants';

// Types
export type {
  PESTELAnalysis,
  PESTELFactor,
  FactorEvidence,
  EnvironmentSignal,
  SignalStatusChange,
  SignalActionItem,
  RegulatoryItem,
  RegulatoryStatusChange,
  ComplianceRequirement,
  RegulatoryDocument,
  Scenario,
  ScenarioDrivingForce,
  ScenarioAssumption,
  EconomicProjection,
  StrategicOption,
  ScenarioSignpost,
  EarlyWarningAlert,
  AlertTrigger,
  AlertNotification,
  TrackedIndicator,
  IndicatorDataPoint,
  EnvironmentScanningAnalytics,
  PESTELAnalysisFilters,
  SignalFilters,
  RegulatoryFilters,
  ScenarioFilters,
  AlertFilters,
  PESTELAnalysisFormInput,
  PESTELFactorFormInput,
  SignalFormInput,
  RegulatoryItemFormInput,
  ScenarioFormInput,
  AlertTriggerFormInput,
} from './types/scanning.types';

// Schemas
export {
  factorEvidenceSchema,
  strategicResponseSchema,
  pestelFactorSchema,
  pestelAnalysisSchema,
  pestelAnalysisUpdateSchema,
  signalSourceDetailsSchema,
  signalAssessmentSchema,
  signalImplicationsSchema,
  signalActionItemSchema,
  signalSchema,
  signalUpdateSchema,
  regulatoryDatesSchema,
  financialImpactSchema,
  regulatoryImpactSchema,
  complianceRequirementSchema,
  complianceSchema,
  regulatoryDocumentSchema,
  regulatoryItemSchema,
  regulatoryItemUpdateSchema,
  drivingForceSchema,
  scenarioAssumptionSchema,
  economicProjectionSchema,
  businessImpactSchema,
  strategicOptionSchema,
  signpostSchema,
  scenarioSchema,
  scenarioUpdateSchema,
  alertTriggerSchema,
  alertTriggerUpdateSchema,
  earlyWarningAlertSchema,
  indicatorThresholdsSchema,
  indicatorDataPointSchema,
  trackedIndicatorSchema,
} from './schemas/scanning.schemas';

export type {
  FactorEvidenceFormData,
  StrategicResponseFormData,
  PESTELFactorFormData,
  PESTELAnalysisFormData,
  SignalFormData,
  SignalActionItemFormData,
  RegulatoryItemFormData,
  ComplianceRequirementFormData,
  ScenarioFormData,
  DrivingForceFormData,
  ScenarioAssumptionFormData,
  EconomicProjectionFormData,
  StrategicOptionFormData,
  SignpostFormData,
  AlertTriggerFormData,
  EarlyWarningAlertFormData,
  TrackedIndicatorFormData,
} from './schemas/scanning.schemas';

// Services
export {
  scanningService,
  createPESTELAnalysis,
  getPESTELAnalysis,
  getPESTELAnalyses,
  updatePESTELAnalysis,
  addPESTELFactor,
  updatePESTELAnalysisStatus,
  generatePESTELSummary,
  createSignal,
  getSignal,
  getSignals,
  updateSignalStatus,
  addSignalActionItem,
  createRegulatoryItem,
  getRegulatoryItem,
  getRegulatoryItems,
  updateRegulatoryStatus,
  updateComplianceStatus,
  getUpcomingDeadlines,
  createScenario,
  getScenario,
  getScenarios,
  updateScenario,
  updateScenarioStatus,
  updateSignpostStatus,
  createAlertTrigger,
  getActiveTriggers,
  createAlert,
  getAlerts,
  acknowledgeAlert,
  resolveAlert,
  trackIndicator,
  updateIndicatorValue,
  getTrackedIndicators,
  getEnvironmentScanningAnalytics,
} from './services/scanningService';

// Hooks
export { useEnvironmentScanning } from './hooks/useEnvironmentScanning';

// Components
export {
  FactorCard,
  ImpactMatrix,
  PESTELDashboard,
  SignalCard,
  SignalFeed,
  RegulationCard,
  ScenarioCard,
  RiskRadar,
  EnvironmentScanningDashboard,
} from './components';

// Pages
export { EnvironmentScanningPage } from './pages';
