// ============================================================================
// KPI LIBRARY CONSTANTS - ZeusOS CEO Strategy Command
// Comprehensive KPI catalog with 50+ industry-standard KPIs
// organized by category with formulas and module linkages
// ============================================================================

import {
  KPICategory,
  KPIType,
  KPIDirection,
  KPIFrequency,
  BSCPerspective,
  KPI_CATEGORY,
  KPI_TYPE,
  KPI_DIRECTION,
  KPI_FREQUENCY,
  BSC_PERSPECTIVE,
} from './kpi.constants';

// ----------------------------------------------------------------------------
// Library Types
// ----------------------------------------------------------------------------

export interface ModuleLinkage {
  module: 'finance' | 'hr' | 'manufacturing' | 'sales' | 'operations';
  dataSourcePath?: string;
  autoComputable: boolean;
  computeHint?: string;
}

export interface KPILibraryEntry {
  id: string;
  code: string;
  name: string;
  description: string;
  formula: string;
  category: KPICategory;
  subCategory: string;
  type: KPIType;
  unit: string;
  direction: KPIDirection;
  frequency: KPIFrequency;
  bscPerspective: BSCPerspective;
  moduleLinkage?: ModuleLinkage;
  tags: string[];
}

export interface KPILibrarySubCategory {
  id: string;
  label: string;
}

export interface KPILibraryCategoryDef {
  id: string;
  label: string;
  icon: string;
  color: string;
  subCategories: KPILibrarySubCategory[];
}

// ----------------------------------------------------------------------------
// Library Categories
// ----------------------------------------------------------------------------

export const KPI_LIBRARY_CATEGORIES: KPILibraryCategoryDef[] = [
  {
    id: 'financial_performance',
    label: 'Financial Performance',
    icon: 'DollarSign',
    color: '#4CAF50',
    subCategories: [
      { id: 'profitability', label: 'Profitability' },
      { id: 'activity', label: 'Activity' },
      { id: 'efficiency', label: 'Efficiency' },
      { id: 'asset_usage', label: 'Asset Usage' },
      { id: 'liquidity', label: 'Liquidity' },
      { id: 'coverage', label: 'Coverage' },
      { id: 'cash_flow', label: 'Cash Flow' },
      { id: 'growth', label: 'Growth' },
      { id: 'value', label: 'Value' },
    ],
  },
  {
    id: 'sales_marketing',
    label: 'Sales & Marketing',
    icon: 'Megaphone',
    color: '#E91E63',
    subCategories: [
      { id: 'sales_performance', label: 'Sales Performance' },
      { id: 'customer_acquisition', label: 'Customer Acquisition' },
      { id: 'marketing_activity', label: 'Marketing Activity' },
    ],
  },
  {
    id: 'customer_success',
    label: 'Customer Success & Experience',
    icon: 'Users',
    color: '#2196F3',
    subCategories: [
      { id: 'satisfaction', label: 'Satisfaction' },
      { id: 'retention', label: 'Retention & Loyalty' },
    ],
  },
  {
    id: 'human_resources',
    label: 'Human Resources',
    icon: 'UserCheck',
    color: '#9C27B0',
    subCategories: [
      { id: 'workforce', label: 'Workforce Stability' },
      { id: 'development', label: 'Development & Performance' },
    ],
  },
  {
    id: 'operations_safety',
    label: 'Operations, Safety & Supply Chain',
    icon: 'Settings',
    color: '#FF9800',
    subCategories: [
      { id: 'production', label: 'Production & Delivery' },
      { id: 'inventory', label: 'Inventory & Quality' },
      { id: 'safety', label: 'Safety' },
    ],
  },
  {
    id: 'healthcare',
    label: 'Healthcare / Clinical',
    icon: 'HeartPulse',
    color: '#009688',
    subCategories: [
      { id: 'patient_care', label: 'Patient Care' },
      { id: 'clinical_ops', label: 'Clinical Operations' },
    ],
  },
];

// ----------------------------------------------------------------------------
// Helper to map library categories to KPI_CATEGORY enum values
// ----------------------------------------------------------------------------

export const LIBRARY_CATEGORY_TO_KPI_CATEGORY: Record<string, KPICategory> = {
  financial_performance: KPI_CATEGORY.FINANCIAL,
  sales_marketing: KPI_CATEGORY.SALES_MARKETING,
  customer_success: KPI_CATEGORY.CUSTOMER,
  human_resources: KPI_CATEGORY.PEOPLE,
  operations_safety: KPI_CATEGORY.OPERATIONAL,
  healthcare: KPI_CATEGORY.HEALTHCARE,
};

// ----------------------------------------------------------------------------
// KPI Library Entries
// ----------------------------------------------------------------------------

export const KPI_LIBRARY: KPILibraryEntry[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // 1. FINANCIAL PERFORMANCE
  // ══════════════════════════════════════════════════════════════════════════

  // ── Profitability ──────────────────────────────────────────────────────
  {
    id: 'FIN_REV',
    code: 'REV',
    name: 'Total Revenue',
    description: 'Sum of all sales and service income generated',
    formula: 'Sum of all sales and service income',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: {
      module: 'finance',
      dataSourcePath: '/finance/overview/kpis',
      autoComputable: true,
      computeHint: 'Computed from QBO P&L data via profitabilityEngine',
    },
    tags: ['revenue', 'income', 'sales', 'top-line'],
  },
  {
    id: 'FIN_GPM',
    code: 'GPM',
    name: 'Gross Profit Margin',
    description: 'Percentage of revenue remaining after cost of goods sold',
    formula: '((Total Revenue - COGS) / Total Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: {
      module: 'finance',
      dataSourcePath: '/finance/overview/kpis',
      autoComputable: true,
      computeHint: 'Computed from QBO P&L data via profitabilityEngine',
    },
    tags: ['margin', 'profit', 'gross', 'cogs'],
  },
  {
    id: 'FIN_OPM',
    code: 'OPM',
    name: 'Operating Profit Margin',
    description: 'Percentage of revenue remaining after operating expenses',
    formula: '(Operating Profit / Total Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: {
      module: 'finance',
      dataSourcePath: '/finance/overview/kpis',
      autoComputable: true,
      computeHint: 'Computed from QBO P&L data via profitabilityEngine',
    },
    tags: ['margin', 'operating', 'profit', 'opex'],
  },
  {
    id: 'FIN_NPM',
    code: 'NPM',
    name: 'Net Profit Margin',
    description: 'Measures overall bottom-line profitability after all expenses',
    formula: '(Net Profit / Total Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: {
      module: 'finance',
      dataSourcePath: '/finance/overview/kpis',
      autoComputable: true,
      computeHint: 'Computed from QBO P&L data via profitabilityEngine',
    },
    tags: ['margin', 'net', 'profit', 'bottom-line'],
  },
  {
    id: 'FIN_ETR',
    code: 'ETR',
    name: 'Expense-to-Revenue Ratio',
    description: 'Measures operational efficiency — lower means better cost control',
    formula: '(Total Operating Expenses / Total Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['expense', 'revenue', 'ratio', 'efficiency'],
  },
  {
    id: 'FIN_NPATM',
    code: 'NPATM',
    name: 'Net Profit After Tax Margin',
    description: 'Net profit after tax as a percentage of revenue',
    formula: '(Net Profit After Tax / Total Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['margin', 'net', 'tax', 'after-tax'],
  },
  {
    id: 'FIN_BEMOS',
    code: 'BEMOS',
    name: 'Breakeven Margin of Safety',
    description: 'Shows how much sales can drop before the business loses money',
    formula: '((Actual Sales - Breakeven Sales) / Actual Sales) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'profitability',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['breakeven', 'safety', 'margin', 'risk'],
  },

  // ── Activity ───────────────────────────────────────────────────────────
  {
    id: 'FIN_AR',
    code: 'AR',
    name: 'Activity Ratio (Asset Turnover)',
    description: 'Measures how efficiently assets generate sales',
    formula: 'Net Sales / Average Total Assets',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'activity',
    type: KPI_TYPE.RATIO,
    unit: 'times',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['activity', 'asset', 'turnover', 'efficiency'],
  },
  {
    id: 'FIN_ARD',
    code: 'ARD',
    name: 'Accounts Receivable Days',
    description: 'Average days to collect payment from customers',
    formula: '(Average Accounts Receivable / Total Credit Sales) × 365',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'activity',
    type: KPI_TYPE.NUMERIC,
    unit: 'days',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['receivable', 'days', 'collection', 'cash-cycle'],
  },
  {
    id: 'FIN_ID',
    code: 'ID',
    name: 'Inventory Days',
    description: 'Average days it takes to sell current inventory',
    formula: '(Average Inventory / Cost of Goods Sold) × 365',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'activity',
    type: KPI_TYPE.NUMERIC,
    unit: 'days',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['inventory', 'days', 'turnover', 'stock'],
  },
  {
    id: 'FIN_APD',
    code: 'APD',
    name: 'Accounts Payable Days',
    description: 'Average days a company takes to pay its suppliers',
    formula: '(Average Accounts Payable / Total Supplier Purchases) × 365',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'activity',
    type: KPI_TYPE.NUMERIC,
    unit: 'days',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['payable', 'days', 'supplier', 'cash-cycle'],
  },

  // ── Efficiency ─────────────────────────────────────────────────────────
  {
    id: 'FIN_ROE',
    code: 'ROE',
    name: 'Return on Equity',
    description: 'Measures profitability relative to shareholders equity',
    formula: '(Net Income / Average Shareholders\' Equity) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'efficiency',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['return', 'equity', 'roe', 'profitability'],
  },
  {
    id: 'FIN_ROCE',
    code: 'ROCE',
    name: 'Return on Capital Employed',
    description: 'EBIT relative to capital employed',
    formula: 'EBIT / (Total Assets - Current Liabilities) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'efficiency',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['return', 'capital', 'roce', 'ebit'],
  },
  {
    id: 'FIN_GMROI',
    code: 'GMROI',
    name: 'Gross Margin Return on Inventory',
    description: 'Gross margin earned for each unit of inventory cost',
    formula: 'Gross Margin / Average Inventory Cost',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'efficiency',
    type: KPI_TYPE.RATIO,
    unit: 'times',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['gmroi', 'inventory', 'margin', 'return'],
  },

  // ── Asset Usage ────────────────────────────────────────────────────────
  {
    id: 'FIN_AT',
    code: 'AT',
    name: 'Asset Turnover',
    description: 'Measures how efficiently assets generate revenue',
    formula: 'Net Sales / Average Total Assets',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'asset_usage',
    type: KPI_TYPE.RATIO,
    unit: 'times',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['asset', 'turnover', 'sales', 'efficiency'],
  },
  {
    id: 'FIN_WCA',
    code: 'WCA',
    name: 'Working Capital Absorption',
    description: 'Percentage of revenue tied up in working capital',
    formula: '(Working Capital / Total Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'asset_usage',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['working-capital', 'absorption', 'revenue'],
  },

  // ── Liquidity ──────────────────────────────────────────────────────────
  {
    id: 'FIN_CR',
    code: 'CR',
    name: 'Current Ratio',
    description: 'Ability to pay short-term obligations (target ~2:1)',
    formula: 'Current Assets / Current Liabilities',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'liquidity',
    type: KPI_TYPE.RATIO,
    unit: ':1',
    direction: KPI_DIRECTION.TARGET_IS_BEST,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['current', 'ratio', 'liquidity', 'solvency'],
  },
  {
    id: 'FIN_QR',
    code: 'QR',
    name: 'Quick Ratio',
    description: 'Ability to pay short-term obligations without inventory (target ~1:1)',
    formula: '(Current Assets - Inventory) / Current Liabilities',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'liquidity',
    type: KPI_TYPE.RATIO,
    unit: ':1',
    direction: KPI_DIRECTION.TARGET_IS_BEST,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['quick', 'ratio', 'liquidity', 'acid-test'],
  },

  // ── Coverage ───────────────────────────────────────────────────────────
  {
    id: 'FIN_IC',
    code: 'IC',
    name: 'Interest Cover',
    description: 'Ability to pay interest on outstanding debt (expressed as multiplier)',
    formula: 'EBIT / Interest Expense',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'coverage',
    type: KPI_TYPE.RATIO,
    unit: 'times',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['interest', 'cover', 'debt', 'solvency'],
  },

  // ── Cash Flow ──────────────────────────────────────────────────────────
  {
    id: 'FIN_COH',
    code: 'COH',
    name: 'Cash on Hand',
    description: 'Sum of cash and cash equivalents available',
    formula: 'Sum of Cash + Cash Equivalents',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'cash_flow',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['cash', 'liquidity', 'reserves'],
  },
  {
    id: 'FIN_CFM',
    code: 'CFM',
    name: 'Cash Flow Margin',
    description: 'Operating cash flow as percentage of net sales',
    formula: '(Operating Cash Flow / Net Sales) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'cash_flow',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['cash-flow', 'margin', 'operating'],
  },
  {
    id: 'FIN_NVCF',
    code: 'NVCF',
    name: 'Net Variable Cash Flow',
    description: 'Operating cash flow minus variable expenses',
    formula: 'Operating Cash Flow - Variable Expenses',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'cash_flow',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['cash-flow', 'variable', 'net'],
  },

  // ── Growth ─────────────────────────────────────────────────────────────
  {
    id: 'FIN_RG',
    code: 'RG',
    name: 'Revenue Growth',
    description: 'Period-over-period change in revenue',
    formula: '((Current Revenue - Previous Revenue) / Previous Revenue) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'growth',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: {
      module: 'finance',
      dataSourcePath: '/finance/overview/growth',
      autoComputable: true,
      computeHint: 'Computed from QBO P&L historical data',
    },
    tags: ['revenue', 'growth', 'top-line'],
  },
  {
    id: 'FIN_COSC',
    code: 'COSC',
    name: 'Cost of Sales Change',
    description: 'Period-over-period change in cost of sales — lower is favorable',
    formula: '((Current COGS - Previous COGS) / Previous COGS) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'growth',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: true },
    tags: ['cogs', 'cost', 'growth', 'change'],
  },
  {
    id: 'FIN_EXPC',
    code: 'EXPC',
    name: 'Expense Change',
    description: 'Period-over-period change in operating expenses — lower is favorable',
    formula: '((Current OpEx - Previous OpEx) / Previous OpEx) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'growth',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: true },
    tags: ['expense', 'opex', 'growth', 'change'],
  },
  {
    id: 'FIN_GPG',
    code: 'GPG',
    name: 'Gross Profit Growth',
    description: 'Period-over-period change in gross profit',
    formula: '((Current GP - Previous GP) / Previous GP) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'growth',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: true },
    tags: ['gross-profit', 'growth'],
  },
  {
    id: 'FIN_OPG',
    code: 'OPG',
    name: 'Operating Profit Growth',
    description: 'Period-over-period change in operating profit',
    formula: '((Current OP - Previous OP) / Previous OP) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'growth',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: true },
    tags: ['operating-profit', 'growth'],
  },
  {
    id: 'FIN_NIG',
    code: 'NIG',
    name: 'Net Income Growth',
    description: 'Period-over-period change in net income',
    formula: '((Current Net Income - Previous Net Income) / Previous) × 100',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'growth',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: true },
    tags: ['net-income', 'growth', 'bottom-line'],
  },

  // ── Value ──────────────────────────────────────────────────────────────
  {
    id: 'FIN_EP',
    code: 'EP',
    name: 'Economic Profit (EVA)',
    description: 'Net operating profit after tax minus cost of capital',
    formula: 'NOPAT - (Invested Capital × WACC)',
    category: KPI_CATEGORY.FINANCIAL,
    subCategory: 'value',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'finance', autoComputable: false },
    tags: ['eva', 'economic-profit', 'value', 'nopat', 'wacc'],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 2. SALES & MARKETING
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'SM_ASPT',
    code: 'ASPT',
    name: 'Average Sales per Transaction',
    description: 'Average revenue generated per sales transaction',
    formula: 'Total Sales Revenue / Total Number of Transactions',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'sales_performance',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    moduleLinkage: { module: 'sales', autoComputable: false },
    tags: ['sales', 'transaction', 'average', 'revenue'],
  },
  {
    id: 'SM_ASPC',
    code: 'ASPC',
    name: 'Average Sales per Customer',
    description: 'Average revenue generated per unique customer',
    formula: 'Total Sales Revenue / Total Unique Customers',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'sales_performance',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['sales', 'customer', 'average', 'revenue'],
  },
  {
    id: 'SM_SPSM',
    code: 'SPSM',
    name: 'Sales per Square Meter',
    description: 'Revenue generated per unit of retail floor space',
    formula: 'Total Retail Revenue / Total Retail Floor Space (sq m)',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'sales_performance',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX/sqm',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    tags: ['sales', 'retail', 'space', 'productivity'],
  },
  {
    id: 'SM_NVRB',
    code: 'NVRB',
    name: 'New vs Repeated Business',
    description: 'Revenue from repeat customers as a percentage of total',
    formula: '(Revenue from Repeat Customers / Total Revenue) × 100',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'customer_acquisition',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['repeat', 'new', 'business', 'retention'],
  },
  {
    id: 'SM_NC',
    code: 'NC',
    name: 'New Customers',
    description: 'Count of newly acquired customers in the period',
    formula: 'Count of newly acquired customers',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'customer_acquisition',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['new', 'customers', 'acquisition'],
  },
  {
    id: 'SM_LC',
    code: 'LC',
    name: 'Lost Customers',
    description: 'Count of customers who stopped buying/cancelled — lower is better',
    formula: 'Count of customers who stopped buying / cancelled',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'customer_acquisition',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['lost', 'customers', 'churn'],
  },
  {
    id: 'SM_REF',
    code: 'REF',
    name: 'Number of Referrals',
    description: 'Customers acquired via existing customer referrals',
    formula: 'Count of referral-sourced customers',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'customer_acquisition',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['referral', 'customers', 'word-of-mouth'],
  },
  {
    id: 'SM_QL',
    code: 'QL',
    name: 'Number of Qualified Leads',
    description: 'Leads that meet predefined sales qualification criteria',
    formula: 'Count of qualified leads',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'marketing_activity',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['leads', 'qualified', 'pipeline'],
  },
  {
    id: 'SM_QP',
    code: 'QP',
    name: 'Number of Quotes/Proposals',
    description: 'Formal quotes submitted to prospects',
    formula: 'Count of quotes / proposals submitted',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'marketing_activity',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['quotes', 'proposals', 'pipeline'],
  },
  {
    id: 'SM_PRES',
    code: 'PRES',
    name: 'Number of Presentations',
    description: 'Sales pitches and demos delivered',
    formula: 'Count of sales presentations / demos',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'marketing_activity',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['presentations', 'demos', 'sales'],
  },
  {
    id: 'SM_CCR',
    code: 'CCR',
    name: 'Customer Conversion Rate',
    description: 'Percentage of leads or quotes that result in a sale',
    formula: '(Number of Successful Sales / Total Leads or Quotes) × 100',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'sales_performance',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['conversion', 'rate', 'sales', 'pipeline'],
  },
  {
    id: 'SM_EMAIL',
    code: 'EMAIL',
    name: 'Email Newsletters Sent',
    description: 'Count of marketing email newsletters dispatched',
    formula: 'Count of email newsletters sent',
    category: KPI_CATEGORY.SALES_MARKETING,
    subCategory: 'marketing_activity',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['email', 'newsletter', 'marketing'],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 3. CUSTOMER SUCCESS & EXPERIENCE
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'CS_COMP',
    code: 'COMP',
    name: 'Number of Complaints',
    description: 'Count of formal customer complaints — lower is better',
    formula: 'Count of logged formal complaints',
    category: KPI_CATEGORY.CUSTOMER,
    subCategory: 'satisfaction',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['complaints', 'customer', 'satisfaction'],
  },
  {
    id: 'CS_COMPLI',
    code: 'COMPLI',
    name: 'Number of Compliments',
    description: 'Count of positive customer feedback/reviews logged',
    formula: 'Count of positive feedback / reviews',
    category: KPI_CATEGORY.CUSTOMER,
    subCategory: 'satisfaction',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['compliments', 'positive', 'feedback'],
  },
  {
    id: 'CS_NPS',
    code: 'NPS',
    name: 'Customer Loyalty (NPS)',
    description: 'Net Promoter Score measuring customer loyalty',
    formula: '% of Promoters - % of Detractors',
    category: KPI_CATEGORY.CUSTOMER,
    subCategory: 'retention',
    type: KPI_TYPE.INDEX,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['nps', 'loyalty', 'promoter', 'customer'],
  },
  {
    id: 'CS_CHURN',
    code: 'CHURN',
    name: 'Customer Attrition (Churn)',
    description: 'Percentage of customers lost during the period — lower is better',
    formula: '(Customers Lost / Total Customers at Start) × 100',
    category: KPI_CATEGORY.CUSTOMER,
    subCategory: 'retention',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['churn', 'attrition', 'retention', 'customer'],
  },
  {
    id: 'CS_CSAT',
    code: 'CSAT',
    name: 'Customer Satisfaction (CSAT)',
    description: 'Percentage of positive survey responses',
    formula: '(Positive Survey Responses / Total Responses) × 100',
    category: KPI_CATEGORY.CUSTOMER,
    subCategory: 'satisfaction',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['csat', 'satisfaction', 'survey', 'customer'],
  },
  {
    id: 'CS_SURV',
    code: 'SURV',
    name: '% Customers Given Satisfaction Surveys',
    description: 'Coverage of customer satisfaction measurement',
    formula: '(Surveys Sent / Total Customer Base) × 100',
    category: KPI_CATEGORY.CUSTOMER,
    subCategory: 'satisfaction',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['survey', 'coverage', 'satisfaction'],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 4. HUMAN RESOURCES
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'HR_TURN',
    code: 'TURN',
    name: 'Staff Turnover',
    description: 'Percentage of employees who left — lower is better',
    formula: '(Employees who Left / Average Employees) × 100',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'workforce',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: {
      module: 'hr',
      dataSourcePath: '/hr/employees',
      autoComputable: false,
      computeHint: 'Can be derived from employee status changes in HR module',
    },
    tags: ['turnover', 'attrition', 'staff', 'hr'],
  },
  {
    id: 'HR_RET',
    code: 'RET',
    name: 'Staff Retention',
    description: 'Percentage of employees who stayed',
    formula: '(Employees Stayed / Total at Start) × 100',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'workforce',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: { module: 'hr', dataSourcePath: '/hr/employees', autoComputable: false },
    tags: ['retention', 'staff', 'hr'],
  },
  {
    id: 'HR_JSAT',
    code: 'JSAT',
    name: 'Job Satisfaction',
    description: 'Average score from employee satisfaction/engagement surveys',
    formula: 'Average employee satisfaction survey score',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'development',
    type: KPI_TYPE.RATING,
    unit: '/5',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: { module: 'hr', dataSourcePath: '/hr/performance/reviews', autoComputable: false },
    tags: ['satisfaction', 'engagement', 'hr', 'survey'],
  },
  {
    id: 'HR_ABS',
    code: 'ABS',
    name: 'Absenteeism',
    description: 'Percentage of unexcused absent days — lower is better',
    formula: '(Unexcused Absent Days / Total Working Days) × 100',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'workforce',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: {
      module: 'hr',
      dataSourcePath: '/hr/leave',
      autoComputable: false,
      computeHint: 'Can be derived from leave management data in HR module',
    },
    tags: ['absenteeism', 'absent', 'leave', 'hr'],
  },
  {
    id: 'HR_TRAIN',
    code: 'TRAIN',
    name: 'Average Training Days per Employee',
    description: 'Investment in employee development',
    formula: 'Total Training Days / Total Employees',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'development',
    type: KPI_TYPE.NUMERIC,
    unit: 'days',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: { module: 'hr', dataSourcePath: '/hr/performance/training', autoComputable: false },
    tags: ['training', 'development', 'learning', 'hr'],
  },
  {
    id: 'HR_PREV',
    code: 'PREV',
    name: 'Staff Performance Reviews Completed',
    description: 'Count of performance appraisals completed',
    formula: 'Count of completed performance reviews',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'development',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: {
      module: 'hr',
      dataSourcePath: '/hr/performance/reviews',
      autoComputable: false,
      computeHint: 'Count from performance review records in HR module',
    },
    tags: ['performance', 'review', 'appraisal', 'hr'],
  },
  {
    id: 'HR_PREVPCT',
    code: 'PREVPCT',
    name: '% Staff Receiving Regular Reviews',
    description: 'Coverage of performance review process',
    formula: '(Employees Reviewed / Total Eligible) × 100',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'development',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.QUARTERLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: { module: 'hr', dataSourcePath: '/hr/performance/reviews', autoComputable: false },
    tags: ['review', 'coverage', 'performance', 'hr'],
  },
  {
    id: 'HR_HC',
    code: 'HC',
    name: 'Number of Staff (Headcount)',
    description: 'Total active headcount at end of reporting period',
    formula: 'Count of active employees',
    category: KPI_CATEGORY.PEOPLE,
    subCategory: 'workforce',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.TARGET_IS_BEST,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.LEARNING_GROWTH,
    moduleLinkage: {
      module: 'hr',
      dataSourcePath: '/hr/employees',
      autoComputable: false,
      computeHint: 'Count from active employee records in HR module',
    },
    tags: ['headcount', 'staff', 'employees', 'hr'],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 5. OPERATIONS, SAFETY & SUPPLY CHAIN
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'OPS_AVAIL',
    code: 'AVAIL',
    name: 'Availability (Uptime)',
    description: 'Percentage of time equipment/systems are operational',
    formula: '(Actual Operational Time / Planned Operational Time) × 100',
    category: KPI_CATEGORY.OPERATIONAL,
    subCategory: 'production',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.WEEKLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    moduleLinkage: { module: 'manufacturing', autoComputable: false },
    tags: ['uptime', 'availability', 'equipment', 'oee'],
  },
  {
    id: 'OPS_DOWN',
    code: 'DOWN',
    name: 'Downtime',
    description: 'Total hours/minutes equipment or systems are non-operational — lower is better',
    formula: 'Total non-operational hours / minutes',
    category: KPI_CATEGORY.OPERATIONAL,
    subCategory: 'production',
    type: KPI_TYPE.NUMERIC,
    unit: 'hours',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.WEEKLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    moduleLinkage: { module: 'manufacturing', autoComputable: false },
    tags: ['downtime', 'equipment', 'outage'],
  },
  {
    id: 'OPS_DIFOT',
    code: 'DIFOT',
    name: 'On-Time Delivery (DIFOT)',
    description: 'Orders delivered in-full and on-time',
    formula: '(Orders Delivered In-Full & On-Time / Total Orders) × 100',
    category: KPI_CATEGORY.OPERATIONAL,
    subCategory: 'production',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.WEEKLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    moduleLinkage: { module: 'manufacturing', autoComputable: true, computeHint: 'Computed from manufacturing order completion dates vs due dates' },
    tags: ['delivery', 'on-time', 'difot', 'fulfillment'],
  },
  {
    id: 'OPS_REWORK',
    code: 'REWORK',
    name: '% Orders Requiring Rework',
    description: 'Orders sent back for corrections — lower is better',
    formula: '(Rework Orders / Total Orders) × 100',
    category: KPI_CATEGORY.QUALITY,
    subCategory: 'inventory',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.WEEKLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    moduleLinkage: { module: 'manufacturing', autoComputable: true, computeHint: 'Computed from rework count on manufacturing orders' },
    tags: ['rework', 'quality', 'defect', 'orders'],
  },
  {
    id: 'OPS_STOCK',
    code: 'STOCK',
    name: 'Number of Stockouts',
    description: 'Times active inventory items reached zero when demanded — lower is better',
    formula: 'Count of stockout events',
    category: KPI_CATEGORY.OPERATIONAL,
    subCategory: 'inventory',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    moduleLinkage: { module: 'manufacturing', autoComputable: false },
    tags: ['stockout', 'inventory', 'supply-chain'],
  },
  {
    id: 'OPS_OCT',
    code: 'OCT',
    name: 'Average Order Completion Time',
    description: 'Average time to complete an order — lower is better',
    formula: 'Total Fulfillment Time / Total Orders',
    category: KPI_CATEGORY.OPERATIONAL,
    subCategory: 'production',
    type: KPI_TYPE.NUMERIC,
    unit: 'days',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.WEEKLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    moduleLinkage: { module: 'manufacturing', autoComputable: true, computeHint: 'Computed from average manufacturing order cycle time (createdAt → completedAt)' },
    tags: ['order', 'completion', 'lead-time', 'cycle'],
  },
  {
    id: 'OPS_ACC',
    code: 'ACC',
    name: 'Safety Incidents',
    description: 'Number of workplace accidents or safety incidents — lower is better',
    formula: 'Count of logged safety incidents',
    category: KPI_CATEGORY.QUALITY,
    subCategory: 'safety',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['safety', 'accident', 'incident', 'ohs'],
  },
  {
    id: 'OPS_LTI',
    code: 'LTI',
    name: 'Lost Time Due to Injuries',
    description: 'Working hours/days lost due to workplace injuries — lower is better',
    formula: 'Total days lost due to workplace injuries',
    category: KPI_CATEGORY.QUALITY,
    subCategory: 'safety',
    type: KPI_TYPE.NUMERIC,
    unit: 'days',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['lost-time', 'injury', 'safety', 'ohs'],
  },
  {
    id: 'OPS_SI',
    code: 'SI',
    name: 'Safety Inspections Completed',
    description: 'Routine safety checks or audits performed',
    formula: 'Count of safety inspections completed',
    category: KPI_CATEGORY.QUALITY,
    subCategory: 'safety',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['safety', 'inspection', 'audit', 'compliance'],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 6. HEALTHCARE / CLINICAL
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'HC_ACPD',
    code: 'ACPD',
    name: 'Average Cost per Discharge',
    description: 'Total operating costs per discharged patient — lower is better',
    formula: 'Total Operating Costs / Total Discharged Patients',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'clinical_ops',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    tags: ['healthcare', 'cost', 'discharge', 'clinical'],
  },
  {
    id: 'HC_ATC',
    code: 'ATC',
    name: 'Average Treatment Charge',
    description: 'Average revenue per treatment administered',
    formula: 'Total Treatment Revenue / Total Treatments',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'clinical_ops',
    type: KPI_TYPE.CURRENCY,
    unit: 'UGX',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.FINANCIAL,
    tags: ['healthcare', 'treatment', 'charge', 'revenue'],
  },
  {
    id: 'HC_NOSHOW',
    code: 'NOSHOW',
    name: 'Non-Attendance Rate (No-Shows)',
    description: 'Percentage of missed appointments — lower is better',
    formula: '(Missed Appointments / Total Scheduled) × 100',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'patient_care',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.LOWER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['healthcare', 'no-show', 'attendance', 'appointment'],
  },
  {
    id: 'HC_PAT',
    code: 'PAT',
    name: 'Number of Patients',
    description: 'Unique patients seen in the period',
    formula: 'Count of unique patients',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'patient_care',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['healthcare', 'patients', 'volume'],
  },
  {
    id: 'HC_DISC',
    code: 'DISC',
    name: 'Patients Discharged',
    description: 'Count of successfully discharged patients',
    formula: 'Count of discharged patients',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'patient_care',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['healthcare', 'discharge', 'patients'],
  },
  {
    id: 'HC_TREAT',
    code: 'TREAT',
    name: 'Number of Treatments',
    description: 'Total procedures/treatments performed',
    formula: 'Count of treatments administered',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'clinical_ops',
    type: KPI_TYPE.NUMERIC,
    unit: '',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['healthcare', 'treatment', 'procedure', 'volume'],
  },
  {
    id: 'HC_OCC',
    code: 'OCC',
    name: 'Occupancy Rate',
    description: 'Percentage of available beds occupied',
    formula: '(Occupied Beds / Total Available Beds) × 100',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'clinical_ops',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.TARGET_IS_BEST,
    frequency: KPI_FREQUENCY.DAILY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['healthcare', 'occupancy', 'beds', 'capacity'],
  },
  {
    id: 'HC_PSAT',
    code: 'PSAT',
    name: 'Patient Satisfaction',
    description: 'Patient satisfaction survey score',
    formula: '(Positive Patient Scores / Total Surveys) × 100',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'patient_care',
    type: KPI_TYPE.PERCENTAGE,
    unit: '%',
    direction: KPI_DIRECTION.HIGHER_IS_BETTER,
    frequency: KPI_FREQUENCY.MONTHLY,
    bscPerspective: BSC_PERSPECTIVE.CUSTOMER,
    tags: ['healthcare', 'patient', 'satisfaction', 'survey'],
  },
  {
    id: 'HC_SPR',
    code: 'SPR',
    name: 'Staff-to-Patient Ratio',
    description: 'Medical staff on duty per patient (expressed as 1:X)',
    formula: 'Total Medical Staff / Total Patients',
    category: KPI_CATEGORY.HEALTHCARE,
    subCategory: 'clinical_ops',
    type: KPI_TYPE.RATIO,
    unit: ':1',
    direction: KPI_DIRECTION.TARGET_IS_BEST,
    frequency: KPI_FREQUENCY.DAILY,
    bscPerspective: BSC_PERSPECTIVE.INTERNAL_PROCESS,
    tags: ['healthcare', 'staffing', 'ratio', 'patient'],
  },
];

// ----------------------------------------------------------------------------
// Utility: Get library entries by library category ID
// ----------------------------------------------------------------------------

export function getLibraryEntriesByCategory(libraryCategoryId: string): KPILibraryEntry[] {
  const kpiCategory = LIBRARY_CATEGORY_TO_KPI_CATEGORY[libraryCategoryId];
  if (!kpiCategory) return [];
  return KPI_LIBRARY.filter((entry) => entry.category === kpiCategory);
}

// ----------------------------------------------------------------------------
// Utility: Get library entries by sub-category
// ----------------------------------------------------------------------------

export function getLibraryEntriesBySubCategory(subCategoryId: string): KPILibraryEntry[] {
  return KPI_LIBRARY.filter((entry) => entry.subCategory === subCategoryId);
}

// ----------------------------------------------------------------------------
// Utility: Search library entries
// ----------------------------------------------------------------------------

export function searchLibraryEntries(query: string): KPILibraryEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return KPI_LIBRARY;
  return KPI_LIBRARY.filter(
    (entry) =>
      entry.name.toLowerCase().includes(q) ||
      entry.code.toLowerCase().includes(q) ||
      entry.description.toLowerCase().includes(q) ||
      entry.formula.toLowerCase().includes(q) ||
      entry.tags.some((tag) => tag.includes(q))
  );
}
