/**
 * Phase 3 — tests for the handoff bundle service.
 *
 * Covers the behaviour contracts the audit's Phase 3 verification step
 * calls out:
 *   - zero-input → throws a clear error (nothing to hand off)
 *   - deterministic content hash
 *   - idempotent reuse on identical hash (second call returns the same bundle)
 *   - previous handoff-bundle docs are excluded from re-bundling
 *   - constituent files are flipped to `status='approved'` (the freeze)
 *   - bundle is auto-shared to the portal
 *   - `linkBundleToMO` writes `handoffBundleFileId` + `projectFileIds` onto the MO
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { ManagedFile } from '@/shared/services/fileManager';

// ── Mocks ─────────────────────────────────────────────────────────────

vi.mock('@/shared/services/fileManager', () => ({
  uploadManagedFile: vi.fn(),
  getProjectFiles: vi.fn(),
  updateFileStatus: vi.fn(() => Promise.resolve()),
  togglePortalSharing: vi.fn(() => Promise.resolve()),
}));

// `buildPolicyName` is pure — don't mock, let it run.
vi.mock('@/shared/services/firebase/firestore', () => ({
  db: {},
}));

// Minimal jszip mock — returns an object with `.file(path, blob)` recorder
// and a `.generateAsync()` that yields a deterministic stub Blob.
vi.mock('jszip', () => {
  return {
    default: class {
      files: Array<{ path: string; blob: Blob | string }> = [];
      file(path: string, blob: Blob | string) {
        this.files.push({ path, blob });
      }
      generateAsync(_opts: unknown) {
        return Promise.resolve(new Blob([`zip:${this.files.length}`], { type: 'application/zip' }));
      }
    },
  };
});

// Stub global fetch used by `fetchFileBlob`
const originalFetch = globalThis.fetch;
beforeEach(() => {
  globalThis.fetch = vi.fn(() =>
    Promise.resolve({
      ok: true,
      blob: () => Promise.resolve(new Blob(['data'])),
    } as unknown as Response),
  );
});
afterEach(() => {
  globalThis.fetch = originalFetch;
});

import {
  createHandoffBundle,
  linkBundleToMO,
} from '../handoffBundleService';
import {
  uploadManagedFile,
  getProjectFiles,
  updateFileStatus,
  togglePortalSharing,
} from '@/shared/services/fileManager';
import { updateDoc } from 'firebase/firestore';

const uploadManagedFileMock = uploadManagedFile as unknown as ReturnType<typeof vi.fn>;
const getProjectFilesMock = getProjectFiles as unknown as ReturnType<typeof vi.fn>;
const updateFileStatusMock = updateFileStatus as unknown as ReturnType<typeof vi.fn>;
const togglePortalSharingMock = togglePortalSharing as unknown as ReturnType<typeof vi.fn>;
const updateDocMock = updateDoc as unknown as ReturnType<typeof vi.fn>;

// ── Helpers ───────────────────────────────────────────────────────────

function makeFile(overrides: Partial<ManagedFile>): ManagedFile {
  return {
    id: overrides.id || 'f1',
    name: overrides.name || 'DF-2025-001-DWG-kitchen-v01-20260419.pdf',
    fileName: overrides.fileName || 'kitchen.pdf',
    fileSize: overrides.fileSize ?? 1024,
    mimeType: overrides.mimeType || 'application/pdf',
    storagePath: overrides.storagePath || 'project-files/p1/deliverable/1_abc_kitchen.pdf',
    storageUrl: overrides.storageUrl || 'https://storage/kitchen.pdf',
    projectId: overrides.projectId || 'p1',
    itemId: overrides.itemId || 'i1',
    module: overrides.module || 'design-manager',
    category: overrides.category || 'deliverable',
    version: overrides.version ?? 1,
    isLatest: overrides.isLatest ?? true,
    isAutoGenerated: overrides.isAutoGenerated ?? false,
    deliverableType: overrides.deliverableType,
    uploadedAt: overrides.uploadedAt || ({} as ManagedFile['uploadedAt']),
    uploadedBy: overrides.uploadedBy || 'u1',
    updatedAt: overrides.updatedAt || ({} as ManagedFile['updatedAt']),
    autoGenHash: overrides.autoGenHash,
    ...overrides,
  } as ManagedFile;
}

function mockUploadReturns(id: string, url = 'https://storage/bundle.zip') {
  uploadManagedFileMock.mockReturnValue({
    promise: Promise.resolve({
      id,
      storageUrl: url,
      name: 'bundle',
      fileName: 'bundle.zip',
    }),
    abort: () => {},
  });
}

// ── Tests ─────────────────────────────────────────────────────────────

describe('createHandoffBundle', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('throws when there are no files to bundle', async () => {
    getProjectFilesMock.mockResolvedValue([]);
    await expect(
      createHandoffBundle({
        projectId: 'p1',
        projectCode: 'DF-2025-001',
        itemId: 'i1',
        itemName: 'Kitchen Remodel',
        userId: 'u1',
      }),
    ).rejects.toThrow(/no latest files to bundle/);
  });

  it('excludes prior handoff-bundle files from being re-bundled', async () => {
    getProjectFilesMock.mockResolvedValue([
      makeFile({ id: 'f-dwg', deliverableType: 'shop-drawing' }),
      makeFile({ id: 'f-bun-old', deliverableType: 'handoff-bundle' }),
    ]);
    mockUploadReturns('f-bun-new');

    const result = await createHandoffBundle({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen',
      userId: 'u1',
    });

    // Only `f-dwg` should be a constituent; the prior bundle is ignored.
    expect(result.constituentFileIds).toEqual(['f-dwg']);
    expect(result.reused).toBe(false);
  });

  it('is idempotent — reuses an existing bundle with matching hash', async () => {
    // Step 1: create a bundle to learn its hash.
    getProjectFilesMock.mockResolvedValue([
      makeFile({ id: 'f-dwg', version: 1 }),
      makeFile({ id: 'f-bom', version: 2 }),
    ]);
    mockUploadReturns('bundle-1');
    const first = await createHandoffBundle({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen',
      userId: 'u1',
    });

    // Step 2: second call with the SAME inputs + a pre-existing bundle
    // whose autoGenHash is the one computed for the same inputs.
    const hash = uploadManagedFileMock.mock.calls[0][1].autoGenHash as string;
    expect(typeof hash).toBe('string');
    expect(hash).toHaveLength(64); // sha-256 hex
    getProjectFilesMock.mockResolvedValue([
      makeFile({ id: 'f-dwg', version: 1 }),
      makeFile({ id: 'f-bom', version: 2 }),
      makeFile({
        id: 'bundle-1',
        deliverableType: 'handoff-bundle',
        autoGenHash: hash,
        storageUrl: 'https://storage/bundle-1.zip',
      }),
    ]);
    uploadManagedFileMock.mockClear();

    const second = await createHandoffBundle({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen',
      userId: 'u1',
    });

    expect(second.reused).toBe(true);
    expect(second.bundleFileId).toBe('bundle-1');
    // No new upload when reused.
    expect(uploadManagedFileMock).not.toHaveBeenCalled();
    // And the first call identity is preserved.
    expect(first.reused).toBe(false);
  });

  it('flips the bundle to approved AND shares it to the portal', async () => {
    getProjectFilesMock.mockResolvedValue([makeFile({ id: 'f-dwg' })]);
    mockUploadReturns('bundle-new');

    await createHandoffBundle({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen',
      userId: 'u-handoff',
    });

    // Bundle doc flipped to approved (first call)
    expect(updateFileStatusMock.mock.calls[0]).toEqual([
      'bundle-new',
      'approved',
      'u-handoff',
    ]);
    expect(togglePortalSharingMock).toHaveBeenCalledWith(
      'bundle-new',
      true,
      'u-handoff',
      expect.stringMatching(/\.zip$/),
    );
  });

  it('freezes every constituent file (status=approved)', async () => {
    getProjectFilesMock.mockResolvedValue([
      makeFile({ id: 'a' }),
      makeFile({ id: 'b' }),
      makeFile({ id: 'c' }),
    ]);
    mockUploadReturns('bundle-new');

    await createHandoffBundle({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen',
      userId: 'u1',
    });

    // First call is the bundle itself; subsequent calls are the constituents.
    const constituentCalls = updateFileStatusMock.mock.calls.slice(1);
    const frozenIds = constituentCalls.map((c: unknown[]) => c[0]).sort();
    expect(frozenIds).toEqual(['a', 'b', 'c']);
    for (const call of constituentCalls) {
      expect(call[1]).toBe('approved');
    }
  });

  it('passes handoff metadata into uploadManagedFile correctly', async () => {
    getProjectFilesMock.mockResolvedValue([makeFile({ id: 'only' })]);
    mockUploadReturns('bundle-new');

    await createHandoffBundle({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen Remodel',
      userId: 'u1',
      userName: 'Alice',
      manufacturingOrderId: 'mo-42',
    });

    const [, ctx] = uploadManagedFileMock.mock.calls[0];
    expect(ctx).toMatchObject({
      projectId: 'p1',
      projectCode: 'DF-2025-001',
      itemId: 'i1',
      itemName: 'Kitchen Remodel',
      manufacturingOrderId: 'mo-42',
      module: 'manufacturing',
      category: 'production-doc',
      deliverableType: 'handoff-bundle',
      isAutoGenerated: true,
      autoGenSource: 'handoff',
      uploadedBy: 'u1',
      uploadedByName: 'Alice',
    });
    // policyName matches the v4 pattern for HANDOFF deliverables.
    expect(ctx.policyName).toMatch(
      /^DF-2025-001-HANDOFF-kitchen-remodel-v01-\d{8}\.zip$/,
    );
  });
});

describe('linkBundleToMO', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('writes handoffBundleFileId + projectFileIds onto the MO (deduped)', async () => {
    await linkBundleToMO('mo-42', 'bundle-1', ['bundle-1', 'f-a', 'f-b', 'f-a']);

    expect(updateDocMock).toHaveBeenCalledTimes(1);
    const [, update] = updateDocMock.mock.calls[0] as [unknown, Record<string, unknown>];
    expect(update.handoffBundleFileId).toBe('bundle-1');
    // Dedupes; bundle-1 appears once, f-a once.
    expect(new Set(update.projectFileIds as string[])).toEqual(
      new Set(['bundle-1', 'f-a', 'f-b']),
    );
  });
});

// Keep `afterEach` import alive for global fetch teardown above.
import { afterEach } from 'vitest';
