/**
 * Produce `RevisionEntry[]` (the shape RevisionTimeline.tsx consumes)
 * from the canonical Phase 3 data sources — `projectFiles` + the
 * Phase 3b `revisionRequests` collection.
 *
 * Kept pure (no Firestore I/O) so it can be unit-tested cheaply and
 * reused by any surface that hosts the timeline (currently the Design
 * Manager's file tab; later possibly the Workshop Viewer session
 * detail).
 */

import type { ManagedFile } from '@/shared/services/fileManager';
import type {
  RevisionEntry,
  RevisionStatus,
  GenerationSource,
} from '@/subsidiaries/finishes/design-studio/types/workshop-viewer.types';
import type { RevisionRequest } from '../types/revisionRequest';

// ─── File → entry ─────────────────────────────────────────────────────

/**
 * Map `ManagedFile.status` → the RevisionTimeline's status enum.
 * Files without an explicit status fall back to 'draft'; approved
 * files are 'final'; review pending → 'in_review'.
 */
function fileStatusToRevision(status?: ManagedFile['status']): RevisionStatus {
  switch (status) {
    case 'approved':
      return 'final';
    case 'review':
      return 'in_review';
    case 'superseded':
    case 'draft':
    default:
      return 'draft';
  }
}

/** Map deliverable/category → the RevisionTimeline's source enum. */
function fileSourceToRevision(file: ManagedFile): GenerationSource {
  if (file.isAutoGenerated) {
    // Workshop-viewer and handoff-bundle look the same to the viewer —
    // both are "the system made this".
    if (file.autoGenSource === 'workshop-viewer' || file.deliverableType === '3d-model') {
      return 'ai_mesh';
    }
    return 'parametric';
  }
  return 'manual_upload';
}

/** Derive a short note line from the file so the timeline shows provenance. */
function noteForFile(file: ManagedFile): string {
  const parts: string[] = [];
  if (file.deliverableType) parts.push(file.deliverableType.replace(/-/g, ' '));
  if (file.fileName) parts.push(file.fileName);
  if (file.uploadedByName) parts.push(`by ${file.uploadedByName}`);
  return parts.join(' · ');
}

function msOf(ts: ManagedFile['uploadedAt'] | RevisionRequest['createdAt']): number {
  return ts?.toMillis ? ts.toMillis() : 0;
}

// ─── Request → entry ──────────────────────────────────────────────────

function requestStatusToRevision(status: RevisionRequest['status']): RevisionStatus {
  switch (status) {
    case 'pending':
    case 'acknowledged':
      return 'editing';
    case 'resolved':
      return 'final';
    case 'declined':
      return 'draft';
  }
}

// ─── Main ─────────────────────────────────────────────────────────────

export interface BuildTimelineInput {
  files: ManagedFile[];
  requests: RevisionRequest[];
}

/**
 * Merge files + requests into a single chronologically-sorted
 * `RevisionEntry[]`. Each file becomes one entry (the current version
 * only — version history is handled by the file manager's dedicated
 * dialog); each request becomes one entry capturing the client
 * feedback moment.
 *
 * `revisionNumber` is a **timeline sequence number**, not a file's
 * own `version` — the UI shows them as R1, R2, R3 reading top-to-bottom.
 */
export function buildRevisionTimeline({
  files,
  requests,
}: BuildTimelineInput): RevisionEntry[] {
  const entries: Array<RevisionEntry & { _ms: number }> = [];

  // Exclude handoff bundles from the timeline rows — they'd create a
  // duplicate "final" entry that shadows whatever the approved
  // constituent files already show. The bundle's existence surfaces via
  // `summariseRevisions().hasHandoffBundle` in the file-manager header.
  for (const file of files) {
    if (file.deliverableType === 'handoff-bundle') continue;
    entries.push({
      id: `file:${file.id}`,
      revisionNumber: 0, // filled after sort
      status: fileStatusToRevision(file.status),
      source: fileSourceToRevision(file),
      createdAt: new Date(msOf(file.uploadedAt) || Date.now()).toISOString(),
      createdBy: file.uploadedByName || file.uploadedBy,
      editNotes: noteForFile(file),
      _ms: msOf(file.uploadedAt),
    });
  }

  for (const req of requests) {
    entries.push({
      id: `req:${req.id}`,
      revisionNumber: 0,
      status: requestStatusToRevision(req.status),
      source: 'external_edit',
      createdAt: new Date(msOf(req.createdAt) || Date.now()).toISOString(),
      createdBy: req.requestedByName || 'Client',
      editNotes: `Revision request: ${req.message}${req.resolvedNote ? ` — ${req.resolvedNote}` : ''}`,
      _ms: msOf(req.createdAt),
    });
  }

  // Chronological — oldest first, so R1 is the first thing that
  // happened and the latest entry ends up at the bottom.
  entries.sort((a, b) => a._ms - b._ms);
  return entries.map((e, idx) => {
    const { _ms, ...rest } = e;
    return { ...rest, revisionNumber: idx + 1 };
  });
}
