/**
 * Handoff Bundle Service (Phase 3).
 *
 * At manufacturing handoff, produces an immutable ZIP snapshot of
 * every `isLatest` `projectFiles` doc belonging to the design item —
 * drawings, specs, CAD models, print packages, the lot — and uploads
 * the ZIP as a new `projectFiles` doc with:
 *
 *   category         = 'production-doc'
 *   deliverableType  = 'handoff-bundle'
 *   status           = 'approved'        (immutable, per Phase 1 lock)
 *   sharedToPortal   = true              (client sees the final package)
 *   isAutoGenerated  = true
 *   autoGenSource    = 'handoff'
 *   autoGenHash      = sha-256 of (id|version) pairs of inputs
 *
 * The bundle's own `status='approved'` marking, combined with Phase 1's
 * approval lock, means the snapshot is genuinely tamper-proof: no
 * non-admin can replace, overwrite, or delete it. Each constituent file
 * is ALSO flipped to `status='approved'` during the same run so the
 * live files likewise freeze at handoff time — no subsequent silent
 * edit can diverge the workshop copy from the client-signed copy.
 *
 * The bundle becomes the canonical Phase 2 Drive mirror entry for the
 * `05_Production/` subfolder per `Dawin-Shared-Drive-Architecture v3`.
 *
 * Idempotency: if an approved bundle already exists for the item with
 * a matching content hash, we return that one instead of creating a
 * second. Callers (handoverService) skip re-handoff when the MO
 * already records a `handoffBundleFileId`, so this layer is the
 * secondary safety net.
 */

import {
  doc,
  updateDoc,
  serverTimestamp,
} from 'firebase/firestore';
import { db } from '@/shared/services/firebase/firestore';
import {
  uploadManagedFile,
  getProjectFiles,
  updateFileStatus,
  togglePortalSharing,
  type ManagedFile,
} from '@/shared/services/fileManager';
import { buildPolicyName } from '@/shared/services/fileManager/namingPolicy';

export interface CreateHandoffBundleArgs {
  projectId: string;
  /** Policy-compliant project code, e.g. "DF-2025-001". */
  projectCode?: string;
  /** Firestore ID of the `designItems/{id}` doc being handed off. */
  itemId: string;
  /** Human-readable item name, used in the bundle filename + display name. */
  itemName: string;
  /** Auth UID of the user initiating handoff — becomes `uploadedBy`. */
  userId: string;
  userName?: string;
  /** Optional MO ID — stamped onto the bundle doc for traceability. */
  manufacturingOrderId?: string;
}

export interface HandoffBundleResult {
  bundleFileId: string;
  bundleStorageUrl: string;
  /** IDs of every `projectFiles` doc included in the ZIP. */
  constituentFileIds: string[];
  /** True when an existing bundle with matching content hash was reused. */
  reused: boolean;
}

// ─── Helpers ──────────────────────────────────────────────────────────

/**
 * Compute a deterministic fingerprint of the input file set so two
 * handoffs with identical inputs produce the same `autoGenHash` — the
 * idempotency check relies on this.
 */
async function hashInputs(files: ManagedFile[]): Promise<string> {
  const input = files
    .map((f) => `${f.id}|${f.version}`)
    .sort()
    .join('\n');
  const bytes = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  const hex = Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
  return hex;
}

/**
 * Fetch blob bytes from a storage URL. Wrapped in its own function so
 * tests can mock it.
 */
async function fetchFileBlob(file: ManagedFile): Promise<Blob | null> {
  try {
    const resp = await fetch(file.storageUrl);
    if (!resp.ok) return null;
    return await resp.blob();
  } catch {
    return null;
  }
}

/** Group files by deliverable type for a readable folder structure inside the ZIP. */
function groupKey(file: ManagedFile): string {
  if (file.deliverableType) return String(file.deliverableType);
  if (file.category) return String(file.category);
  return 'other';
}

// ─── Main ─────────────────────────────────────────────────────────────

/**
 * Build + upload the handoff bundle. Idempotent — if an existing
 * bundle with the same content hash already exists for the item it is
 * returned instead of creating a duplicate.
 *
 * Throws when there are zero files to bundle (nothing to hand off) so
 * callers can surface a clear "add a drawing first" error.
 */
export async function createHandoffBundle(
  args: CreateHandoffBundleArgs,
): Promise<HandoffBundleResult> {
  const { projectId, projectCode, itemId, itemName, userId, userName, manufacturingOrderId } = args;

  // 1. Collect every latest file for this design item.
  const allFiles = await getProjectFiles(projectId, { itemId, isLatest: true });
  // Exclude any prior handoff bundles from the input set — we never want
  // to nest yesterday's bundle inside today's.
  const inputs = allFiles.filter((f) => f.deliverableType !== 'handoff-bundle');
  if (inputs.length === 0) {
    throw new Error(
      `Cannot create handoff bundle — item "${itemName}" has no latest files to bundle.`,
    );
  }

  const hash = await hashInputs(inputs);

  // 2. Idempotency check — is there already an approved handoff bundle
  //    for this item with the same input hash? If so, reuse it.
  const existingBundles = allFiles.filter(
    (f) => f.deliverableType === 'handoff-bundle' && f.autoGenHash === hash,
  );
  if (existingBundles.length > 0) {
    const hit = existingBundles[0];
    return {
      bundleFileId: hit.id,
      bundleStorageUrl: hit.storageUrl,
      constituentFileIds: inputs.map((f) => f.id),
      reused: true,
    };
  }

  // 3. Build the ZIP in-memory. Dynamic-import `jszip` to match the
  //    `downloadFilesAsZip` pattern in fileManagerService.
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();

  const manifest: Array<{
    id: string;
    name: string;
    fileName: string;
    version: number;
    category: string;
    deliverableType: string | null;
    fileSize: number;
  }> = [];

  for (const file of inputs) {
    const blob = await fetchFileBlob(file);
    if (!blob) continue; // skip unfetchable files; manifest records them via absence
    const folder = groupKey(file);
    const entryName = file.name || file.fileName;
    zip.file(`${folder}/${entryName}`, blob);
    manifest.push({
      id: file.id,
      name: file.name,
      fileName: file.fileName,
      version: file.version,
      category: file.category,
      deliverableType: file.deliverableType || null,
      fileSize: file.fileSize,
    });
  }

  // MANIFEST.json at the bundle root — lists what's inside + provenance.
  zip.file(
    'MANIFEST.json',
    JSON.stringify(
      {
        bundleFor: { projectId, projectCode, itemId, itemName },
        manufacturingOrderId: manufacturingOrderId || null,
        generatedAt: new Date().toISOString(),
        generatedBy: userId,
        generatedByName: userName || null,
        inputHash: hash,
        files: manifest,
      },
      null,
      2,
    ),
  );

  const zipBlob = await zip.generateAsync({ type: 'blob' });
  const bundleFileName = buildPolicyName({
    projectCode: projectCode || 'UNKNOWN',
    typeCode: 'HANDOFF',
    description: itemName || 'handoff',
    version: 1,
    extension: 'zip',
  });
  const bundleFile = new File([zipBlob], bundleFileName, { type: 'application/zip' });

  // 4. Upload via the unified file manager — Drive mirror trigger fires
  //    automatically (Phase 2) and files the bundle under `05_Production/`
  //    via the `category='production-doc'` routing.
  const { promise } = uploadManagedFile(bundleFile, {
    projectId,
    projectCode,
    itemId,
    itemName,
    manufacturingOrderId,
    module: 'manufacturing',
    category: 'production-doc',
    deliverableType: 'handoff-bundle',
    policyName: bundleFileName,
    uploadedBy: userId,
    uploadedByName: userName,
    isAutoGenerated: true,
    autoGenSource: 'handoff',
    autoGenHash: hash,
    tags: ['handoff', 'immutable-snapshot'],
  });
  const bundleDoc = await promise;

  // 5. Immediately flip the bundle to status='approved'. The service
  //    approval-lock + Firestore rule then make it tamper-proof.
  await updateFileStatus(bundleDoc.id, 'approved', userId);
  // Auto-share to the client portal so the client sees the final
  // production-ready package the moment handoff happens.
  await togglePortalSharing(bundleDoc.id, true, userId, bundleFileName);

  // 6. Mark every constituent file as approved too — so the live files
  //    freeze in lockstep with the bundle. Each `updateFileStatus` call
  //    is independent; we swallow per-file failures so one missing write
  //    doesn't unwind the whole handoff (the bundle itself is already
  //    the immutable record of truth).
  await Promise.all(
    inputs.map((f) =>
      updateFileStatus(f.id, 'approved', userId).catch((err) => {
        console.warn(`[Handoff] Failed to freeze file ${f.id}:`, err);
      }),
    ),
  );

  return {
    bundleFileId: bundleDoc.id,
    bundleStorageUrl: bundleDoc.storageUrl,
    constituentFileIds: inputs.map((f) => f.id),
    reused: false,
  };
}

/**
 * Stamp the bundle ID (plus every constituent file ID) onto the MO so
 * downstream consumers can resolve the canonical file refs without
 * walking `projectFiles` themselves. Safe to call even if
 * `handoffBundleFileId` is already set — idempotent in practice.
 */
export async function linkBundleToMO(
  moId: string,
  bundleFileId: string,
  constituentFileIds: string[],
): Promise<void> {
  await updateDoc(doc(db, 'manufacturingOrders', moId), {
    handoffBundleFileId: bundleFileId,
    projectFileIds: Array.from(new Set([bundleFileId, ...constituentFileIds])),
    updatedAt: serverTimestamp(),
  });
}
