/**
 * Phase 4b — approval-lock admin-override service-level tests.
 *
 * Phase 1 shipped the `allowApprovedOverride` parameter on
 * `replaceFile` + `overwriteFile` but had no UI surface to exercise
 * it. Phase 4b added the checkbox in `FileUploadDialog`; these tests
 * lock in the service-level behaviour:
 *
 *   - `replaceFile` with `status='approved'` throws by default
 *   - `replaceFile` with `allowApprovedOverride=true` proceeds
 *   - same for `overwriteFile`
 *
 * We mock Firestore at the module level (handled by vitest.config's
 * `firebase/firestore` alias → src/firebase/__mocks__) and Firebase
 * Storage at the module level.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { getDoc, doc } from 'firebase/firestore';

// Stub Firebase Storage — never hit the network.
vi.mock('firebase/storage', () => ({
  ref: vi.fn(() => 'mock-ref'),
  uploadBytesResumable: vi.fn(() => {
    const task: any = Promise.resolve();
    task.on = vi.fn();
    task.cancel = vi.fn();
    task.snapshot = { ref: 'mock-ref' };
    return task;
  }),
  getDownloadURL: vi.fn(() => Promise.resolve('https://s/x')),
  deleteObject: vi.fn(() => Promise.resolve()),
}));

vi.mock('@/shared/services/firebase', () => ({ storage: {} }));
vi.mock('@/shared/services/firebase/firestore', () => ({ db: {} }));

import { replaceFile, overwriteFile } from '../fileManagerService';

const getDocMock = getDoc as unknown as ReturnType<typeof vi.fn>;

function makeExisting(overrides: Record<string, unknown> = {}) {
  return {
    exists: () => true,
    id: 'existing-id',
    data: () => ({
      id: 'existing-id',
      name: 'DF-2025-001-DWG-x-v01-20260419.pdf',
      fileName: 'x.pdf',
      fileSize: 100,
      mimeType: 'application/pdf',
      storagePath: 'project-files/p1/deliverable/OLD',
      storageUrl: 'https://s/OLD',
      projectId: 'p1',
      itemId: 'i1',
      module: 'design-manager',
      category: 'deliverable',
      version: 1,
      isLatest: true,
      isAutoGenerated: false,
      status: 'approved',
      uploadedBy: 'u1',
      ...overrides,
    }),
  };
}

function makeFile() {
  return new File([new Uint8Array([1, 2, 3])], 'new.pdf', { type: 'application/pdf' });
}

describe('approval lock — replaceFile', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('throws by default when existing file is approved', async () => {
    getDocMock.mockResolvedValue(makeExisting());
    await expect(replaceFile('existing-id', makeFile(), 'u1')).rejects.toThrow(/approved/i);
  });

  it('proceeds when allowApprovedOverride=true', async () => {
    // getDoc is called twice: once for the existing file, once post-batch for the new doc.
    getDocMock
      .mockResolvedValueOnce(makeExisting())
      .mockResolvedValueOnce({
        exists: () => true,
        id: 'new-id',
        data: () => ({ uploadedAt: {}, updatedAt: {} }),
      });
    const result = await replaceFile('existing-id', makeFile(), 'u1', undefined, true);
    expect(result).toBeDefined();
    expect(result.version).toBe(2);
  });

  it('proceeds when existing file is NOT approved (irrespective of override)', async () => {
    getDocMock
      .mockResolvedValueOnce(makeExisting({ status: 'draft' }))
      .mockResolvedValueOnce({
        exists: () => true,
        id: 'new-id',
        data: () => ({ uploadedAt: {}, updatedAt: {} }),
      });
    const result = await replaceFile('existing-id', makeFile(), 'u1');
    expect(result.version).toBe(2);
  });
});

describe('approval lock — overwriteFile', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('throws by default when existing file is approved', async () => {
    getDocMock.mockResolvedValue(makeExisting());
    await expect(
      overwriteFile('existing-id', makeFile(), undefined, 'u1'),
    ).rejects.toThrow(/approved/i);
  });

  it('proceeds when allowApprovedOverride=true', async () => {
    getDocMock.mockResolvedValue(makeExisting());
    const result = await overwriteFile(
      'existing-id',
      makeFile(),
      undefined,
      'u1',
      undefined,
      true,
    );
    expect(result).toBeDefined();
  });
});

// Keep the `doc` import referenced so tsc doesn't prune it — it's
// pulled in for completeness even though we mock firestore globally.
void doc;
