/**
 * Pure-function tests for summariseRevisions + formatRelativeDate.
 */
import { describe, it, expect } from 'vitest';
import { summariseRevisions, formatRelativeDate } from '../revisionSummary';
import type { ManagedFile } from '../types';

function file(
  overrides: Partial<ManagedFile> & { version?: number; uploadedAtMs?: number },
): ManagedFile {
  const uploadedAtMs = overrides.uploadedAtMs;
  return {
    id: overrides.id || 'f',
    name: overrides.name || 'DF-2025-001-DWG-x-v01-20260419.pdf',
    fileName: overrides.fileName || 'x.pdf',
    fileSize: overrides.fileSize ?? 1,
    mimeType: overrides.mimeType || 'application/pdf',
    storagePath: overrides.storagePath || 'project-files/p1/deliverable/x',
    storageUrl: overrides.storageUrl || 'https://s/x',
    projectId: overrides.projectId || 'p1',
    itemId: overrides.itemId || 'i1',
    module: overrides.module || 'design-manager',
    category: overrides.category || 'deliverable',
    version: overrides.version ?? 1,
    isLatest: overrides.isLatest ?? true,
    isAutoGenerated: overrides.isAutoGenerated ?? false,
    uploadedAt: uploadedAtMs
      ? ({
          toMillis: () => uploadedAtMs,
          toDate: () => new Date(uploadedAtMs),
          seconds: Math.floor(uploadedAtMs / 1000),
          nanoseconds: 0,
        } as ManagedFile['uploadedAt'])
      : ({} as ManagedFile['uploadedAt']),
    uploadedBy: overrides.uploadedBy || 'u1',
    updatedAt: overrides.updatedAt || ({} as ManagedFile['updatedAt']),
    ...overrides,
  } as ManagedFile;
}

describe('summariseRevisions', () => {
  it('empty input → zeros, null timestamp, all false', () => {
    expect(summariseRevisions([])).toEqual({
      currentRevision: 0,
      fileCount: 0,
      lastRevisedAtMs: null,
      hasApprovedFiles: false,
      hasHandoffBundle: false,
    });
  });

  it('takes max version across inputs', () => {
    const s = summariseRevisions([
      file({ id: 'a', version: 1 }),
      file({ id: 'b', version: 4 }),
      file({ id: 'c', version: 2 }),
    ]);
    expect(s.currentRevision).toBe(4);
    expect(s.fileCount).toBe(3);
  });

  it('takes max uploadedAt (most recent)', () => {
    const now = Date.now();
    const s = summariseRevisions([
      file({ id: 'old', uploadedAtMs: now - 1000000 }),
      file({ id: 'new', uploadedAtMs: now - 1000 }),
      file({ id: 'mid', uploadedAtMs: now - 500000 }),
    ]);
    expect(s.lastRevisedAtMs).toBe(now - 1000);
  });

  it('hasApprovedFiles true when any file is status=approved', () => {
    const s = summariseRevisions([
      file({ id: 'a', status: 'draft' }),
      file({ id: 'b', status: 'approved' }),
    ]);
    expect(s.hasApprovedFiles).toBe(true);
  });

  it('hasHandoffBundle true when any file is deliverableType=handoff-bundle', () => {
    const s = summariseRevisions([
      file({ id: 'a', deliverableType: 'shop-drawing' }),
      file({ id: 'b', deliverableType: 'handoff-bundle' }),
    ]);
    expect(s.hasHandoffBundle).toBe(true);
  });
});

describe('formatRelativeDate', () => {
  it('null / undefined → empty string', () => {
    expect(formatRelativeDate(null)).toBe('');
    expect(formatRelativeDate(undefined)).toBe('');
  });
  it('now → today', () => {
    expect(formatRelativeDate(Date.now())).toBe('today');
  });
  it('1 day ago → yesterday', () => {
    expect(formatRelativeDate(Date.now() - 1000 * 60 * 60 * 24 - 1000)).toBe('yesterday');
  });
  it('7 days ago → 7d ago', () => {
    expect(formatRelativeDate(Date.now() - 7 * 24 * 60 * 60 * 1000 - 1000)).toBe('7d ago');
  });
  it('>30 days → locale date string', () => {
    const s = formatRelativeDate(Date.now() - 40 * 24 * 60 * 60 * 1000);
    expect(s).toMatch(/\d/); // at least contains a digit
    expect(s).not.toBe('today');
  });
});
