/**
 * Deliverable Attachment Service
 *
 * Handles saving Workshop Viewer print packages as deliverables on
 * design items and as reference documents on manufacturing orders.
 *
 * Phase 3 — these functions now route the primary write through
 * `uploadManagedFile` (the unified File Manager) so:
 *   - the PDF lands in `projectFiles` (single source of truth, F-A6)
 *   - the Phase 2 Drive-mirror trigger fires (Drive sync at no cost)
 *   - the file gets a policy-compliant name (Naming Policy v4)
 *   - approval lock + versioning come along for free.
 *
 * The legacy paths (`createDeliverable` into the `designItems/{id}/deliverables`
 * subcollection, and `referenceDocuments[]` on the MO doc) are STILL
 * written for backward compatibility during the dual-write window — any
 * existing reader that walks either of those sources keeps working.
 * Phase 4 will remove the legacy writes once readers are migrated.
 */

import {
  doc,
  updateDoc,
  collection,
  arrayUnion,
  Timestamp,
  query,
  where,
  getDocs,
} from 'firebase/firestore';
import { db } from '@/firebase/config';
import { createDeliverable } from '@/modules/design-manager/services';
import type { DeliverableType, DesignStage } from '@/modules/design-manager/types';
import type { MOReferenceDocument } from '@/modules/manufacturing/types';
import { uploadManagedFile } from '@/shared/services/fileManager';
import { buildPolicyName } from '@/shared/services/fileManager/namingPolicy';

// ---------------------------------------------------------------------------
// Attach print package as a deliverable on a design item
// ---------------------------------------------------------------------------

export async function attachPrintPackageAsDeliverable(params: {
  projectId: string;
  /** Policy-compliant project code for the unified File Manager entry. */
  projectCode?: string;
  itemId: string;
  itemName?: string;
  pdfBlob: Blob;
  fileName: string;
  sessionId: string;
  userId: string;
  userName?: string;
  stage?: string;
}): Promise<{
  deliverableId: string;
  storageUrl: string;
  /** Phase 3 — the `projectFiles` doc ID (new canonical source of truth). */
  projectFileId: string;
}> {
  const {
    projectId,
    projectCode,
    itemId,
    itemName,
    pdfBlob,
    fileName,
    sessionId,
    userId,
    userName,
    stage,
  } = params;
  const resolvedStage = stage || 'production-ready';

  // 1. Primary write — through the unified File Manager.
  //    This inherits Phase 1 naming enforcement + Phase 2 Drive mirror
  //    + per-file version chain + approval lock.
  const policyName = buildPolicyName({
    projectCode: projectCode || 'UNKNOWN',
    typeCode: 'DWG',
    description: itemName || fileName.replace(/\.[^.]+$/, ''),
    version: 1,
    extension: 'pdf',
  });
  const pdfFile = new File([pdfBlob], policyName, { type: 'application/pdf' });
  const { promise } = uploadManagedFile(pdfFile, {
    projectId,
    projectCode,
    itemId,
    itemName,
    module: 'design-manager',
    category: 'deliverable',
    deliverableType: 'shop-drawing',
    policyName,
    uploadedBy: userId,
    uploadedByName: userName,
    isAutoGenerated: true,
    autoGenSource: 'workshop-viewer',
    tags: ['workshop-viewer', `session:${sessionId}`],
  });
  const managedFile = await promise;

  // 2. Legacy subcollection write — kept for backward compat so any
  //    existing reader of `designItems/{id}/deliverables` still sees
  //    the file. Uses the same storageUrl as the unified doc so there
  //    is ONE canonical blob in storage (not a duplicate).
  //
  //    Phase 4 todo: remove this once all readers have migrated to
  //    `projectFiles`.
  let deliverableId = '';
  try {
    deliverableId = await createDeliverable(
      projectId,
      itemId,
      {
        name: fileName,
        type: 'shop-drawing' as DeliverableType,
        description: `Workshop Viewer print package (session: ${sessionId})`,
        fileName,
        fileType: 'application/pdf',
        fileSize: pdfBlob.size,
        mimeType: 'application/pdf',
        storageUrl: managedFile.storageUrl,
        storagePath: managedFile.storagePath,
        isAutoGenerated: true,
        autoGenSource: 'workshop-viewer',
      },
      userId,
      resolvedStage as DesignStage,
    );
  } catch (err) {
    // The legacy write is non-critical — the unified file manager
    // already has the file and will drive RAG updates via its own
    // built-in trigger. Log so operators can track dual-write drift.
    console.warn(
      '[deliverableAttachmentService] Legacy createDeliverable() write failed — unified copy is intact:',
      err,
    );
  }

  return {
    deliverableId,
    storageUrl: managedFile.storageUrl,
    projectFileId: managedFile.id,
  };
}

// ---------------------------------------------------------------------------
// Attach print package as a reference document on a manufacturing order
// ---------------------------------------------------------------------------

export async function attachPrintPackageToMO(params: {
  moId: string;
  projectId: string;
  projectCode?: string;
  itemId?: string;
  itemName?: string;
  pdfBlob: Blob;
  fileName: string;
  sessionId: string;
  userId: string;
  userName?: string;
}): Promise<{
  storageUrl: string;
  projectFileId: string;
}> {
  const {
    moId,
    projectId,
    projectCode,
    itemId,
    itemName,
    pdfBlob,
    fileName,
    sessionId,
    userId,
    userName,
  } = params;

  // 1. Primary write — unified File Manager. Routed to `05_Production/`
  //    via the Phase 2 subfolder resolver (`production-doc` + MO context).
  const policyName = buildPolicyName({
    projectCode: projectCode || 'UNKNOWN',
    typeCode: 'DWG',
    description: itemName || fileName.replace(/\.[^.]+$/, ''),
    version: 1,
    extension: 'pdf',
  });
  const pdfFile = new File([pdfBlob], policyName, { type: 'application/pdf' });
  const { promise } = uploadManagedFile(pdfFile, {
    projectId,
    projectCode,
    itemId,
    itemName,
    manufacturingOrderId: moId,
    module: 'manufacturing',
    category: 'production-doc',
    deliverableType: 'shop-drawing',
    policyName,
    uploadedBy: userId,
    uploadedByName: userName,
    isAutoGenerated: true,
    autoGenSource: 'workshop-viewer',
    tags: ['workshop-viewer', 'mo-reference', `session:${sessionId}`],
  });
  const managedFile = await promise;

  // 2. Legacy MO.referenceDocuments write — kept for backward compat.
  //    The canonical FK going forward is `MO.projectFileIds` (Phase 3)
  //    populated by the handoff bundle service.
  try {
    const refDoc: MOReferenceDocument = {
      id: managedFile.id, // use the projectFiles id — stable and cross-referencable
      type: 'print-package',
      name: fileName,
      storageUrl: managedFile.storageUrl,
      storagePath: managedFile.storagePath,
      source: 'workshop-viewer',
      sourceSessionId: sessionId,
      createdAt: Timestamp.now(),
      createdBy: userId,
    };
    const moRef = doc(db, 'manufacturingOrders', moId);
    await updateDoc(moRef, {
      referenceDocuments: arrayUnion(refDoc),
      projectFileIds: arrayUnion(managedFile.id),
    });
  } catch (err) {
    console.warn(
      '[deliverableAttachmentService] Legacy MO.referenceDocuments write failed — unified copy is intact:',
      err,
    );
  }

  return { storageUrl: managedFile.storageUrl, projectFileId: managedFile.id };
}

// ---------------------------------------------------------------------------
// Get linked workshop sessions for a design item
// ---------------------------------------------------------------------------

export async function getLinkedWorkshopSessions(
  designItemId: string,
): Promise<Array<{ sessionId: string; lastPrintPackageUrl?: string }>> {
  const sessionsRef = collection(db, 'workshop_viewer_sessions');
  const q = query(sessionsRef, where('linkedDesignItemId', '==', designItemId));
  const snapshot = await getDocs(q);

  const results: Array<{ sessionId: string; lastPrintPackageUrl?: string }> = [];

  for (const docSnap of snapshot.docs) {
    const data = docSnap.data();
    if (data.lastPrintPackageUrl) {
      results.push({
        sessionId: docSnap.id,
        lastPrintPackageUrl: data.lastPrintPackageUrl,
      });
    }
  }

  return results;
}
