/**
 * Tests for revisionTimelineBuilder.
 * Covers: merge of files + requests, chronological ordering, exclusion
 * of handoff-bundle files, status / source mapping.
 */
import { describe, it, expect } from 'vitest';
import { buildRevisionTimeline } from '../revisionTimelineBuilder';
import type { ManagedFile } from '@/shared/services/fileManager';
import type { RevisionRequest } from '../../types/revisionRequest';

function fileAt(ms: number, overrides: Partial<ManagedFile> = {}): ManagedFile {
  return {
    id: overrides.id || `f-${ms}`,
    name: overrides.name || 'x',
    fileName: overrides.fileName || 'x.pdf',
    fileSize: 1,
    mimeType: 'application/pdf',
    storagePath: 'p/x',
    storageUrl: 's/x',
    projectId: 'p1',
    itemId: 'i1',
    module: 'design-manager',
    category: 'deliverable',
    version: 1,
    isLatest: true,
    isAutoGenerated: false,
    uploadedAt: {
      toMillis: () => ms,
      toDate: () => new Date(ms),
      seconds: Math.floor(ms / 1000),
      nanoseconds: 0,
    } as ManagedFile['uploadedAt'],
    uploadedBy: 'u1',
    updatedAt: {} as ManagedFile['updatedAt'],
    ...overrides,
  } as ManagedFile;
}

function reqAt(ms: number, overrides: Partial<RevisionRequest> = {}): RevisionRequest {
  return {
    id: overrides.id || `r-${ms}`,
    projectId: 'p1',
    itemId: 'i1',
    requestedBy: 'client',
    message: 'please change',
    status: 'pending',
    createdAt: {
      toMillis: () => ms,
    } as RevisionRequest['createdAt'],
    updatedAt: {} as RevisionRequest['updatedAt'],
    ...overrides,
  };
}

describe('buildRevisionTimeline', () => {
  it('merges + sorts chronologically, assigns R1..Rn numbers', () => {
    const timeline = buildRevisionTimeline({
      files: [fileAt(1000), fileAt(3000), fileAt(5000)],
      requests: [reqAt(2000), reqAt(4000)],
    });
    expect(timeline.map((t) => t.revisionNumber)).toEqual([1, 2, 3, 4, 5]);
    // Oldest → newest ordering.
    expect(new Date(timeline[0].createdAt).getTime()).toBe(1000);
    expect(new Date(timeline[timeline.length - 1].createdAt).getTime()).toBe(5000);
  });

  it('excludes handoff-bundle files from timeline rows', () => {
    const timeline = buildRevisionTimeline({
      files: [
        fileAt(1000, { id: 'dwg', deliverableType: 'shop-drawing' }),
        fileAt(2000, { id: 'bundle', deliverableType: 'handoff-bundle' }),
      ],
      requests: [],
    });
    expect(timeline.map((t) => t.id)).toEqual(['file:dwg']);
  });

  it('maps file.status → RevisionStatus', () => {
    const t = buildRevisionTimeline({
      files: [
        fileAt(1000, { id: 'd', status: 'draft' }),
        fileAt(2000, { id: 'r', status: 'review' }),
        fileAt(3000, { id: 'a', status: 'approved' }),
      ],
      requests: [],
    });
    expect(t[0].status).toBe('draft');
    expect(t[1].status).toBe('in_review');
    expect(t[2].status).toBe('final');
  });

  it('maps auto-gen workshop-viewer file → source=ai_mesh', () => {
    const t = buildRevisionTimeline({
      files: [
        fileAt(1000, {
          id: 'x',
          isAutoGenerated: true,
          autoGenSource: 'workshop-viewer',
        }),
      ],
      requests: [],
    });
    expect(t[0].source).toBe('ai_mesh');
  });

  it('maps request.status → RevisionStatus (editing/final/draft)', () => {
    const t = buildRevisionTimeline({
      files: [],
      requests: [
        reqAt(1000, { id: 'a', status: 'pending' }),
        reqAt(2000, { id: 'b', status: 'acknowledged' }),
        reqAt(3000, { id: 'c', status: 'resolved' }),
        reqAt(4000, { id: 'd', status: 'declined' }),
      ],
    });
    expect(t[0].status).toBe('editing');
    expect(t[1].status).toBe('editing');
    expect(t[2].status).toBe('final');
    expect(t[3].status).toBe('draft');
    // All requests get source='external_edit'.
    for (const entry of t) expect(entry.source).toBe('external_edit');
  });

  it('encodes provenance in editNotes', () => {
    const t = buildRevisionTimeline({
      files: [
        fileAt(1000, {
          id: 'f',
          fileName: 'kitchen.dwg',
          deliverableType: 'shop-drawing',
          uploadedByName: 'Alice',
        }),
      ],
      requests: [],
    });
    expect(t[0].editNotes).toContain('shop drawing');
    expect(t[0].editNotes).toContain('kitchen.dwg');
    expect(t[0].editNotes).toContain('Alice');
  });
});
