/**
 * /procurement/journal-entries — Parent-org viewer for GL postings made
 * by the Phase 4.1 finance consumer (postJournalEntryOnInvoicePaid).
 *
 * Each row is a double-entry against the chart of accounts. Used by
 * finance to verify GL postings match the operational ledger.
 */

import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/core/hooks/useAuth';
import { listJournalEntries, isBalanced } from '../services/journal-entry.service';
import type { JournalEntry, JournalEntryKind } from '../types/journal-entry.types';

const DEFAULT_ORG_ID = 'default';

const KIND_OPTIONS: Array<JournalEntryKind | 'ALL'> = [
  'ALL', 'TALENT_FREELANCER', 'MEDIA_SUPPLIER', 'CLIENT_REVENUE_RECOGNISED',
];

const KIND_LABEL: Record<JournalEntryKind | 'ALL', string> = {
  ALL: 'All kinds',
  TALENT_FREELANCER: 'Talent',
  MEDIA_SUPPLIER: 'Media',
  CLIENT_REVENUE_RECOGNISED: 'Client Revenue',
};

function formatMoney(minor: number, currency: string): string {
  return `${currency} ${(minor / 100).toLocaleString(undefined, { minimumFractionDigits: 0 })}`;
}

function formatDate(value: unknown): string {
  if (!value) return '—';
  if (typeof value === 'string') return value.slice(0, 10);
  const ts = value as { seconds?: number; toDate?: () => Date };
  if (typeof ts.toDate === 'function') return ts.toDate().toISOString().slice(0, 10);
  if (typeof ts.seconds === 'number') return new Date(ts.seconds * 1000).toISOString().slice(0, 10);
  return '—';
}

function totalDebits(je: JournalEntry): number {
  return je.debits.reduce((sum, line) => sum + line.amountMinor, 0);
}

export default function JournalEntriesListPage() {
  const { user } = useAuth();
  const orgId = (user as { organizationId?: string })?.organizationId || DEFAULT_ORG_ID;

  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [kindFilter, setKindFilter] = useState<JournalEntryKind | 'ALL'>('ALL');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function reload() {
    if (!user) return;
    setLoading(true);
    setError(null);
    try {
      const rows = await listJournalEntries({
        orgId,
        kind: kindFilter === 'ALL' ? undefined : kindFilter,
      });
      setEntries(rows);
    } catch (err) {
      setError(String((err as Error).message));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { reload(); }, [user, orgId, kindFilter]);

  return (
    <div className="space-y-6 p-6">
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold">Journal Entries</h1>
          <p className="text-sm text-muted-foreground">
            GL postings auto-generated by the Phase 4.1 finance consumer. Each entry is
            a balanced double-entry against the chart of accounts.
          </p>
        </div>
        <select
          value={kindFilter}
          onChange={(e) => setKindFilter(e.target.value as JournalEntryKind | 'ALL')}
          className="rounded border px-2 py-1 text-sm"
          data-testid="je-kind-filter"
        >
          {KIND_OPTIONS.map((k) => (
            <option key={k} value={k}>{KIND_LABEL[k]}</option>
          ))}
        </select>
      </header>

      {loading && <p className="text-sm text-muted-foreground">Loading journal entries…</p>}
      {error && <p className="text-sm text-destructive">Error: {error}</p>}

      {!loading && !error && entries.length === 0 && (
        <div className="rounded border border-dashed p-6 text-center text-sm text-muted-foreground">
          No journal entries yet. They are posted automatically after purchase orders are raised
          or client invoices are paid.
        </div>
      )}

      {!loading && !error && entries.length > 0 && (
        <div className="overflow-x-auto rounded border">
          <table className="w-full text-sm" data-testid="je-table">
            <thead className="bg-muted/50">
              <tr className="text-left text-xs uppercase text-muted-foreground">
                <th className="px-4 py-2 font-medium">Entry ID</th>
                <th className="px-4 py-2 font-medium">Kind</th>
                <th className="px-4 py-2 font-medium">Source</th>
                <th className="px-4 py-2 font-medium">Amount</th>
                <th className="px-4 py-2 font-medium">Balance</th>
                <th className="px-4 py-2 font-medium">Posted</th>
              </tr>
            </thead>
            <tbody>
              {entries.map((je) => (
                <tr
                  key={je.id}
                  className="border-t hover:bg-muted/30"
                  data-je-id={je.id}
                  data-je-source-po={je.sourceDocId}
                >
                  <td className="px-4 py-2 font-mono text-xs">
                    <Link to={`/procurement/journal-entries/${je.id}`} className="hover:underline">
                      {je.id}
                    </Link>
                  </td>
                  <td className="px-4 py-2 text-xs">{KIND_LABEL[je.kind]}</td>
                  <td className="px-4 py-2 font-mono text-xs text-muted-foreground">
                    {je.sourceDocId}
                  </td>
                  <td className="px-4 py-2 font-medium">
                    {formatMoney(totalDebits(je), je.currency)}
                  </td>
                  <td className="px-4 py-2 text-xs">
                    {isBalanced(je) ? (
                      <span className="text-emerald-700">Balanced</span>
                    ) : (
                      <span className="text-rose-700">UNBALANCED</span>
                    )}
                  </td>
                  <td className="px-4 py-2 text-xs text-muted-foreground">
                    {formatDate(je.postedAt)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
