/**
 * UnifiedFileManager
 * Cross-module file browser with bulk ops, versioning, upload/replace
 */

import { useState, useEffect, useMemo } from 'react';
import {
  Upload,
  Download,
  Trash2,
  FileText,
  FileImage,
  FileSpreadsheet,
  File as FileIcon,
  MoreVertical,
  History,
  Replace,
  ExternalLink,
  Loader2,
  FolderOpen,
  Grid,
  List,
  Bot,
  CheckCircle,
  Eye,
  Globe,
  Box,
  HardDrive,
} from 'lucide-react';
import { cn } from '@/shared/lib/utils';
import { Checkbox } from '@/core/components/ui/checkbox';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/core/components/ui/dropdown-menu';
import type { ManagedFile, FileCategory } from '@/shared/services/fileManager';
import {
  subscribeToProjectFiles,
  deleteManagedFiles,
  downloadFilesAsZip,
  updateFileStatus,
  togglePortalSharing,
  formatFileSize,
  getFileIconType,
  CATEGORY_LABELS,
  isCadModelFileName,
  summariseRevisions,
  formatRelativeDate,
} from '@/shared/services/fileManager';
import { BulkActionToolbar } from './BulkActionToolbar';
import { FileVersionHistory } from './FileVersionHistory';
import { FileUploadDialog } from './FileUploadDialog';

export interface UnifiedFileManagerProps {
  projectId: string;
  projectCode?: string;
  itemId?: string;
  itemName?: string;
  manufacturingOrderId?: string;
  readOnly?: boolean;
  showBulkActions?: boolean;
  userId: string;
  userName?: string;
  module?: 'design-manager' | 'manufacturing' | 'shared';
}

export function UnifiedFileManager({
  projectId,
  projectCode,
  itemId,
  itemName,
  readOnly = false,
  showBulkActions = true,
  userId,
  userName,
  module = 'design-manager',
}: UnifiedFileManagerProps) {
  const [loading, setLoading] = useState(true);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [viewMode, setViewMode] = useState<'list' | 'grid'>('list');
  const [categoryFilter, setCategoryFilter] = useState<FileCategory | 'all'>('all');
  const [autoGenFilter, setAutoGenFilter] = useState<'all' | 'auto' | 'manual'>('all');
  // Phase 4 — archived files hidden by default; flip to include them.
  const [showArchived, setShowArchived] = useState(false);

  // Dialogs
  const [uploadOpen, setUploadOpen] = useState(false);
  const [replaceTarget, setReplaceTarget] = useState<ManagedFile | undefined>();
  const [versionFile, setVersionFile] = useState<ManagedFile | null>(null);

  // Bulk action states
  const [deleting, setDeleting] = useState(false);
  const [downloading, setDownloading] = useState(false);

  // All raw files from Firestore — stable subscription, only changes on projectId/itemId
  const [rawFiles, setRawFiles] = useState<ManagedFile[]>([]);
  // True when the subscription cap is hit — surfaced as a warning banner so
  // users know some files aren't shown (F-E4 no-silent-truncation guarantee).
  const [truncated, setTruncated] = useState(false);

  useEffect(() => {
    setLoading(true);
    setRawFiles([]);
    setTruncated(false);
    const unsub = subscribeToProjectFiles(
      projectId,
      itemId ? { itemId } : undefined,
      ({ files: next, truncated: tr }) => {
        setRawFiles(next);
        setTruncated(tr);
        setLoading(false);
      }
    );
    return unsub;
  }, [projectId, itemId]); // ← only re-subscribe when scope changes, NOT on filter changes

  // Apply UI filters client-side so filter changes never trigger a new Firestore round-trip
  const files = useMemo(() => {
    let result = rawFiles;
    // Phase 4 — hide archived files unless the user explicitly opts in.
    // The archived flag is set by the archiveProject CF when a project
    // transitions to `status: 'completed'`.
    if (!showArchived) result = result.filter((f) => !f.archived);
    if (categoryFilter !== 'all') result = result.filter((f) => f.category === categoryFilter);
    if (autoGenFilter === 'auto') result = result.filter((f) => f.isAutoGenerated);
    if (autoGenFilter === 'manual') result = result.filter((f) => !f.isAutoGenerated);
    return result;
  }, [rawFiles, categoryFilter, autoGenFilter, showArchived]);

  // Count of hidden archived files — surfaced as a hint next to the toggle.
  const archivedHiddenCount = useMemo(() => {
    if (showArchived) return 0;
    return rawFiles.filter((f) => f.archived).length;
  }, [rawFiles, showArchived]);

  // Phase 3b — derived item revision summary. Only meaningful when an
  // itemId is scoped; at project level the number is "max across
  // every item" which is rarely actionable.
  const itemRevisionSummary = useMemo(
    () => (itemId ? summariseRevisions(rawFiles) : null),
    [itemId, rawFiles],
  );

  // Selection
  const toggleSelect = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (selectedIds.size === files.length) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(files.map((f) => f.id)));
    }
  };

  // Bulk actions
  const handleBulkDelete = async () => {
    if (!confirm(`Delete ${selectedIds.size} file(s)? This cannot be undone.`)) return;
    setDeleting(true);
    const { deleted, failed } = await deleteManagedFiles(Array.from(selectedIds));
    setSelectedIds(new Set());
    setDeleting(false);
    if (failed > 0) {
      // eslint-disable-next-line no-alert -- codebase uses window.alert for status messaging; replace with toast when one is introduced
      alert(`Deleted ${deleted} file(s). ${failed} file(s) failed to delete — you may lack permission or they were already removed.`);
    }
    // The onSnapshot subscription refreshes the list automatically — no manual reload needed.
  };

  const handleBulkDownload = async () => {
    setDownloading(true);
    const selected = files.filter((f) => selectedIds.has(f.id));
    const { failed } = await downloadFilesAsZip(selected, `project-${projectId}-files.zip`);
    setDownloading(false);
    if (failed.length > 0) {
      // eslint-disable-next-line no-alert -- codebase uses window.alert for status messaging; replace with toast when one is introduced
      alert(`ZIP downloaded with ${failed.length} file(s) skipped (fetch failed): ${failed.slice(0, 3).join(', ')}${failed.length > 3 ? ', …' : ''}`);
    }
  };

  // File icon
  const FileIconComponent = ({
    mimeType,
    fileName,
  }: {
    mimeType: string | null | undefined;
    fileName?: string | null;
  }) => {
    const type = getFileIconType(mimeType, fileName);
    switch (type) {
      case 'image': return <FileImage className="h-5 w-5 text-purple-500" />;
      case 'pdf': return <FileText className="h-5 w-5 text-red-500" />;
      case 'spreadsheet': return <FileSpreadsheet className="h-5 w-5 text-emerald-500" />;
      case 'model': return <Box className="h-5 w-5 text-blue-500" />;
      default: return <FileIcon className="h-5 w-5 text-[var(--fg-tertiary)]" />;
    }
  };

  const formatDate = (ts: any) => {
    if (!ts?.toDate) return '';
    const d = ts.toDate();
    const now = new Date();
    const diffMs = now.getTime() - d.getTime();
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    if (diffDays === 0) return 'Today';
    if (diffDays === 1) return 'Yesterday';
    if (diffDays < 30) return `${diffDays}d ago`;
    return d.toLocaleDateString();
  };

  return (
    <div className="space-y-3">
      {/* Toolbar */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-semibold text-muted-foreground">
            Files
          </h3>
          <span className="text-xs text-[var(--fg-tertiary)]">
            {files.length} file{files.length !== 1 ? 's' : ''}
          </span>
          {/* Phase 3b — item-level revision summary (F-D1). Only shown
              when the manager is scoped to a single design item, since
              at project level the "max version" number isn't actionable. */}
          {itemRevisionSummary && itemRevisionSummary.fileCount > 0 && (
            <span className="inline-flex items-center gap-1 text-xs text-muted-foreground">
              <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-[var(--bg-sunken)] text-muted-foreground font-medium">
                v{itemRevisionSummary.currentRevision}
              </span>
              {itemRevisionSummary.lastRevisedAtMs && (
                <span>· revised {formatRelativeDate(itemRevisionSummary.lastRevisedAtMs)}</span>
              )}
              {itemRevisionSummary.hasHandoffBundle && (
                <span className="text-emerald-600 font-medium">· handoff shipped</span>
              )}
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          {/* Filters */}
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value as any)}
            className="text-xs border border-[var(--border-subtle)] rounded-md px-2 py-1.5 bg-card"
          >
            <option value="all">All Categories</option>
            {Object.entries(CATEGORY_LABELS).map(([key, label]) => (
              <option key={key} value={key}>{label}</option>
            ))}
          </select>

          <select
            value={autoGenFilter}
            onChange={(e) => setAutoGenFilter(e.target.value as any)}
            className="text-xs border border-[var(--border-subtle)] rounded-md px-2 py-1.5 bg-card"
          >
            <option value="all">All Sources</option>
            <option value="auto">Auto-generated</option>
            <option value="manual">Manual uploads</option>
          </select>

          {/* Phase 4 — archived toggle. Only renders when there's
              actually something to toggle, so the UI stays clean for
              active-only projects (the vast majority of views). */}
          {(archivedHiddenCount > 0 || showArchived) && (
            <label
              className="inline-flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer select-none"
              title={
                showArchived
                  ? 'Hide files from archived projects'
                  : `Include ${archivedHiddenCount} archived file${archivedHiddenCount === 1 ? '' : 's'}`
              }
            >
              <input
                type="checkbox"
                checked={showArchived}
                onChange={(e) => setShowArchived(e.target.checked)}
                className="accent-[var(--accent)]"
              />
              <span>
                {showArchived ? 'Archived shown' : `Show archived (${archivedHiddenCount})`}
              </span>
            </label>
          )}

          {/* View toggle */}
          <div className="flex border border-[var(--border-subtle)] rounded-md overflow-hidden">
            <button
              onClick={() => setViewMode('list')}
              className={cn('p-1.5', viewMode === 'list' ? 'bg-[var(--bg-sunken)]' : 'hover:bg-[var(--bg-sunken)]')}
            >
              <List className="h-3.5 w-3.5" />
            </button>
            <button
              onClick={() => setViewMode('grid')}
              className={cn('p-1.5', viewMode === 'grid' ? 'bg-[var(--bg-sunken)]' : 'hover:bg-[var(--bg-sunken)]')}
            >
              <Grid className="h-3.5 w-3.5" />
            </button>
          </div>

          {!readOnly && (
            <button
              onClick={() => { setReplaceTarget(undefined); setUploadOpen(true); }}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-background bg-foreground rounded-lg hover:bg-foreground/90"
            >
              <Upload className="h-3.5 w-3.5" />
              Upload
            </button>
          )}
        </div>
      </div>

      {/* Bulk action bar */}
      {showBulkActions && selectedIds.size > 0 && (
        <BulkActionToolbar
          selectedCount={selectedIds.size}
          onDelete={handleBulkDelete}
          onDownloadZip={handleBulkDownload}
          onClearSelection={() => setSelectedIds(new Set())}
          deleting={deleting}
          downloading={downloading}
        />
      )}

      {/* Truncation warning — surfaces silent cap-hit so users aren't blindsided */}
      {truncated && (
        <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
          <span className="font-semibold">Showing the {rawFiles.length} most recent files.</span>
          <span>
            This project has more than the subscription cap — older files are hidden. Use search
            or a tighter filter to find them, or ask an admin for pagination.
          </span>
        </div>
      )}

      {/* Loading */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-5 w-5 animate-spin text-[var(--fg-tertiary)]" />
        </div>
      ) : files.length === 0 ? (
        <div className="text-center py-12 text-[var(--fg-tertiary)]">
          <FolderOpen className="h-10 w-10 mx-auto mb-2" />
          <p className="text-sm">No files yet</p>
          {!readOnly && (
            <button
              onClick={() => setUploadOpen(true)}
              className="mt-2 text-sm text-blue-600 hover:underline"
            >
              Upload your first file
            </button>
          )}
        </div>
      ) : viewMode === 'list' ? (
        /* List view */
        <div className="border border-[var(--border-subtle)] rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-[var(--bg-sunken)] border-b">
              <tr>
                {showBulkActions && (
                  <th className="w-10 px-3 py-2">
                    <Checkbox
                      checked={selectedIds.size === files.length && files.length > 0}
                      onCheckedChange={toggleAll}
                    />
                  </th>
                )}
                <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground">File</th>
                <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground hidden md:table-cell">Category</th>
                <th className="text-left px-3 py-2 text-xs font-medium text-muted-foreground hidden lg:table-cell">Item</th>
                <th className="text-right px-3 py-2 text-xs font-medium text-muted-foreground hidden sm:table-cell">Size</th>
                <th className="text-right px-3 py-2 text-xs font-medium text-muted-foreground">Version</th>
                <th className="text-right px-3 py-2 text-xs font-medium text-muted-foreground hidden sm:table-cell">Date</th>
                <th className="w-10 px-3 py-2" />
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--border-subtle)]">
              {files.map((file) => (
                <tr
                  key={file.id}
                  className={cn(
                    'hover:bg-[var(--bg-sunken)] transition-colors',
                    selectedIds.has(file.id) && 'bg-blue-50',
                    // Phase 4 — archived rows get a muted tint so they
                    // visibly separate from active files when the toggle
                    // is on.
                    file.archived && 'opacity-60',
                  )}
                >
                  {showBulkActions && (
                    <td className="px-3 py-2">
                      <Checkbox
                        checked={selectedIds.has(file.id)}
                        onCheckedChange={() => toggleSelect(file.id)}
                      />
                    </td>
                  )}
                  <td className="px-3 py-2">
                    <div className="flex items-center gap-2 min-w-0">
                      <FileIconComponent mimeType={file.mimeType} fileName={file.fileName} />
                      <div className="min-w-0">
                        <a
                          href={file.storageUrl}
                          download={file.name || file.fileName}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-sm font-medium text-foreground hover:text-blue-600 truncate block"
                        >
                          {file.name || file.fileName}
                        </a>
                        {file.isAutoGenerated && (
                          <span className="inline-flex items-center gap-0.5 text-[10px] text-amber-600">
                            <Bot className="h-3 w-3" /> Auto
                          </span>
                        )}
                        {file.status === 'approved' && (
                          <span className="inline-flex items-center gap-0.5 text-[10px] text-green-600">
                            <CheckCircle className="h-3 w-3" /> Approved
                          </span>
                        )}
                        {file.status === 'review' && (
                          <span className="inline-flex items-center gap-0.5 text-[10px] text-amber-500">
                            <Eye className="h-3 w-3" /> In Review
                          </span>
                        )}
                        {file.sharedToPortal && (
                          <span className="inline-flex items-center gap-0.5 text-[10px] text-blue-500">
                            <Globe className="h-3 w-3" />
                          </span>
                        )}
                        {file.driveWebViewLink && (
                          <span
                            className="inline-flex items-center gap-0.5 text-[10px] text-emerald-600"
                            title={
                              file.driveFolderSubpath
                                ? `Mirrored to Drive · ${file.driveFolderSubpath}`
                                : 'Mirrored to Drive'
                            }
                          >
                            <HardDrive className="h-3 w-3" />
                          </span>
                        )}
                        {!file.driveWebViewLink && file.driveSyncError && (
                          <span
                            className="inline-flex items-center gap-0.5 text-[10px] text-red-500"
                            title={`Drive sync failed: ${file.driveSyncError}`}
                          >
                            <HardDrive className="h-3 w-3" />!
                          </span>
                        )}
                      </div>
                    </div>
                  </td>
                  <td className="px-3 py-2 text-xs text-muted-foreground hidden md:table-cell">
                    {CATEGORY_LABELS[file.category] || file.category}
                  </td>
                  <td className="px-3 py-2 text-xs text-muted-foreground truncate max-w-[120px] hidden lg:table-cell">
                    {file.itemName || '—'}
                  </td>
                  <td className="px-3 py-2 text-xs text-muted-foreground text-right hidden sm:table-cell">
                    {formatFileSize(file.fileSize)}
                  </td>
                  <td className="px-3 py-2 text-right">
                    {file.version > 1 ? (
                      <button
                        onClick={() => setVersionFile(file)}
                        className="inline-flex items-center gap-0.5 text-xs text-blue-600 hover:underline"
                      >
                        v{file.version}
                        <History className="h-3 w-3" />
                      </button>
                    ) : (
                      <span className="text-xs text-[var(--fg-tertiary)]">v1</span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-xs text-[var(--fg-tertiary)] text-right hidden sm:table-cell">
                    {formatDate(file.uploadedAt)}
                  </td>
                  <td className="px-3 py-2">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <button className="p-1 hover:bg-[var(--bg-sunken)] rounded">
                          <MoreVertical className="h-4 w-4 text-[var(--fg-tertiary)]" />
                        </button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end" className="w-44">
                        <DropdownMenuItem asChild>
                          <a
                            href={file.storageUrl}
                            download={file.name || file.fileName}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <Download className="h-3.5 w-3.5 mr-2" /> Download
                          </a>
                        </DropdownMenuItem>
                        {!readOnly && (
                          <DropdownMenuItem
                            onClick={() => {
                              setReplaceTarget(file);
                              setUploadOpen(true);
                            }}
                          >
                            <Replace className="h-3.5 w-3.5 mr-2" /> Replace
                          </DropdownMenuItem>
                        )}
                        {file.version > 1 && (
                          <DropdownMenuItem onClick={() => setVersionFile(file)}>
                            <History className="h-3.5 w-3.5 mr-2" /> Version History
                          </DropdownMenuItem>
                        )}
                        {file.itemId && (
                          <DropdownMenuItem asChild>
                            <a href={`/design/project/${file.projectId}/item/${file.itemId}`}>
                              <ExternalLink className="h-3.5 w-3.5 mr-2" /> View in Design Manager
                            </a>
                          </DropdownMenuItem>
                        )}
                        {/* Drive mirror — present only when the Phase 2 mirror has
                            successfully synced the file to `01_Active-Projects/.../0N_.../`. */}
                        {file.driveWebViewLink && (
                          <DropdownMenuItem asChild>
                            <a
                              href={file.driveWebViewLink}
                              target="_blank"
                              rel="noopener noreferrer"
                              title={
                                file.driveFolderSubpath
                                  ? `Google Drive · ${file.driveFolderSubpath}`
                                  : 'Google Drive'
                              }
                            >
                              <HardDrive className="h-3.5 w-3.5 mr-2" /> Open in Drive
                            </a>
                          </DropdownMenuItem>
                        )}
                        {/* Process in Workshop Viewer — matches any file the viewer
                            can open (CAD extensions OR the `cad-model` category). The
                            category check catches files that were uploaded via the
                            Studio's auto-persist path (which stamps `cad-model`
                            explicitly) even if their filename extension is funky. */}
                        {file.projectId && file.itemId &&
                          (file.category === 'cad-model' || isCadModelFileName(file.fileName)) && (
                          <DropdownMenuItem asChild>
                            <a href={`/workshop?projectId=${encodeURIComponent(file.projectId)}&itemId=${encodeURIComponent(file.itemId)}&fileUrl=${encodeURIComponent(file.storageUrl)}`}>
                              <Box className="h-3.5 w-3.5 mr-2" /> Open in Design Studio
                            </a>
                          </DropdownMenuItem>
                        )}
                        {/* Status controls */}
                        {!readOnly && file.status !== 'approved' && (
                          <DropdownMenuItem
                            onClick={async () => {
                              const next = file.status === 'review' ? 'approved' : 'review';
                              await updateFileStatus(file.id, next, userId);
                            }}
                          >
                            {file.status === 'review' ? (
                              <><CheckCircle className="h-3.5 w-3.5 mr-2 text-green-600" /> Approve</>
                            ) : (
                              <><Eye className="h-3.5 w-3.5 mr-2 text-amber-600" /> Mark for Review</>
                            )}
                          </DropdownMenuItem>
                        )}
                        {/* Portal sharing toggle */}
                        {!readOnly && (
                          <DropdownMenuItem
                            onClick={async () => {
                              const nextShared = !file.sharedToPortal;
                              const confirmMsg = nextShared
                                ? `Share "${file.name || file.fileName}" to the client portal? The client will be able to view and download this file.`
                                : `Remove "${file.name || file.fileName}" from the client portal? The client will no longer see it.`;
                              if (!confirm(confirmMsg)) return;
                              await togglePortalSharing(file.id, nextShared, userId);
                            }}
                          >
                            {file.sharedToPortal ? (
                              <><Globe className="h-3.5 w-3.5 mr-2" /> Remove from Portal</>
                            ) : (
                              <><Globe className="h-3.5 w-3.5 mr-2 text-blue-600" /> Share to Portal</>
                            )}
                          </DropdownMenuItem>
                        )}
                        {!readOnly && (
                          <DropdownMenuItem
                            className="text-red-600"
                            onClick={async () => {
                              if (!confirm(`Delete "${file.name}"?`)) return;
                              const { failed } = await deleteManagedFiles([file.id]);
                              if (failed > 0) {
                                // eslint-disable-next-line no-alert -- codebase uses window.alert; replace with toast when introduced
                                alert(`Failed to delete "${file.name}" — you may lack permission.`);
                              }
                              // Live subscription updates the list automatically.
                            }}
                          >
                            <Trash2 className="h-3.5 w-3.5 mr-2" /> Delete
                          </DropdownMenuItem>
                        )}
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        /* Grid view */
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
          {files.map((file) => (
            <div
              key={file.id}
              className={cn(
                'border rounded-lg p-3 hover:shadow-sm transition-shadow cursor-pointer relative group',
                selectedIds.has(file.id) ? 'border-blue-400 bg-blue-50' : 'border-[var(--border-subtle)]'
              )}
            >
              {showBulkActions && (
                <div className="absolute top-2 left-2">
                  <Checkbox
                    checked={selectedIds.has(file.id)}
                    onCheckedChange={() => toggleSelect(file.id)}
                  />
                </div>
              )}
              <div className="flex flex-col items-center text-center">
                <div className="mb-2 mt-2">
                  <FileIconComponent mimeType={file.mimeType} fileName={file.fileName} />
                </div>
                <a
                  href={file.storageUrl}
                  download={file.name || file.fileName}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs font-medium text-foreground hover:text-blue-600 truncate w-full"
                >
                  {file.name || file.fileName}
                </a>
                <span className="text-[10px] text-[var(--fg-tertiary)] mt-1">
                  {formatFileSize(file.fileSize)}
                  {file.version > 1 && ` · v${file.version}`}
                </span>
                {file.isAutoGenerated && (
                  <span className="inline-flex items-center gap-0.5 text-[10px] text-amber-600 mt-0.5">
                    <Bot className="h-2.5 w-2.5" /> Auto
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Upload dialog */}
      <FileUploadDialog
        open={uploadOpen}
        onClose={() => { setUploadOpen(false); setReplaceTarget(undefined); }}
        projectId={projectId}
        projectCode={projectCode}
        itemId={itemId}
        itemName={itemName}
        module={module}
        replaceTarget={replaceTarget}
        onUploadComplete={() => { /* Live subscription updates the list. */ }}
        userId={userId}
        userName={userName}
      />

      {/* Version history dialog */}
      {versionFile && (
        <FileVersionHistory
          file={versionFile}
          open={!!versionFile}
          onClose={() => setVersionFile(null)}
        />
      )}
    </div>
  );
}
