/**
 * Deliverable Constants
 * Single source of truth for deliverable types, labels, and RAG aspect mappings.
 */

import type { DeliverableType } from '../types';

// ============================================
// Deliverable Types
// ============================================

export const DELIVERABLE_TYPES: { value: DeliverableType; label: string }[] = [
  { value: 'concept-sketch', label: 'Concept Sketch' },
  { value: 'mood-board', label: 'Mood Board' },
  { value: '3d-model', label: '3D Model' },
  { value: 'rendering', label: 'Rendering' },
  { value: 'shop-drawing', label: 'Shop Drawing' },
  { value: 'cut-list', label: 'Cut List' },
  { value: 'bom', label: 'Bill of Materials' },
  { value: 'assembly-instructions', label: 'Assembly Instructions' },
  { value: 'specification-sheet', label: 'Specification Sheet' },
  { value: 'client-presentation', label: 'Client Presentation' },
  { value: 'other', label: 'Other' },
];

export const DELIVERABLE_TYPE_LABELS: Record<DeliverableType, string> = Object.fromEntries(
  DELIVERABLE_TYPES.map(t => [t.value, t.label])
) as Record<DeliverableType, string>;

// ============================================
// Drawing Types (for ShopTraveler PDF)
// ============================================

/**
 * Deliverable types that are auto-generated by the system from project data.
 * These should show distinct "Auto" visuals in the matrix (not upload prompts).
 */
export const AUTO_GENERATED_DELIVERABLE_TYPES: DeliverableType[] = [
  'cut-list',
  'bom',
  'specification-sheet',
  'shop-drawing',
];

/** Deliverable types that represent visual drawings for production PDFs. */
export const DRAWING_DELIVERABLE_TYPES: DeliverableType[] = [
  'shop-drawing',
  'concept-sketch',
  'rendering',
];

/** Image file extensions that can be rendered inline in PDFs. */
export const IMAGE_FILE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'];

// ============================================
// Deliverable-to-RAG Mapping
// ============================================

/**
 * Maps deliverable types to the RAG aspects they auto-update to green.
 * Mirrors DELIVERABLE_TO_RAG_MAP in ragAutoUpdateService.ts.
 */
export const DELIVERABLE_RAG_MAP: Record<string, { path: string; label: string }[]> = {
  'shop-drawing': [
    { path: 'designCompleteness.productionDrawings', label: 'Production Drawings' },
  ],
  'cut-list': [
    { path: 'designCompleteness.productionDrawings', label: 'Production Drawings' },
    { path: 'manufacturingReadiness.processDocumentation', label: 'Process Documentation' },
  ],
  'bom': [
    { path: 'manufacturingReadiness.processDocumentation', label: 'Process Documentation' },
  ],
  'assembly-instructions': [
    { path: 'designCompleteness.assemblyInstructions', label: 'Assembly Instructions' },
  ],
  '3d-model': [
    { path: 'designCompleteness.model3D', label: '3D Model' },
  ],
  'specification-sheet': [
    { path: 'designCompleteness.materialSpecs', label: 'Material Specs' },
  ],
};

/**
 * Flat path-only version for quick lookups (e.g. BulkFileUploadDialog AUTO_RAG_PREVIEW).
 */
export const DELIVERABLE_RAG_PATHS: Record<string, string[]> = Object.fromEntries(
  Object.entries(DELIVERABLE_RAG_MAP).map(([type, aspects]) => [
    type,
    aspects.map(a => a.path),
  ])
);

// ============================================
// All RAG Aspects (for manual overrides)
// ============================================

export const ALL_RAG_ASPECTS: { path: string; label: string }[] = [
  { path: 'designCompleteness.overallDimensions', label: 'Overall Dimensions' },
  { path: 'designCompleteness.model3D', label: '3D Model' },
  { path: 'designCompleteness.productionDrawings', label: 'Production Drawings' },
  { path: 'designCompleteness.materialSpecs', label: 'Material Specs' },
  { path: 'designCompleteness.hardwareSpecs', label: 'Hardware Specs' },
  { path: 'designCompleteness.finishSpecs', label: 'Finish Specs' },
  { path: 'designCompleteness.joineryDetails', label: 'Joinery Details' },
  { path: 'designCompleteness.tolerances', label: 'Tolerances' },
  { path: 'designCompleteness.assemblyInstructions', label: 'Assembly Instructions' },
  { path: 'manufacturingReadiness.materialAvailability', label: 'Material Availability' },
  { path: 'manufacturingReadiness.hardwareAvailability', label: 'Hardware Availability' },
  { path: 'manufacturingReadiness.toolingReadiness', label: 'Tooling Readiness' },
  { path: 'manufacturingReadiness.processDocumentation', label: 'Process Documentation' },
  { path: 'manufacturingReadiness.qualityCriteria', label: 'Quality Criteria' },
  { path: 'manufacturingReadiness.costValidation', label: 'Cost Validation' },
  { path: 'qualityGates.internalDesignReview', label: 'Internal Design Review' },
  { path: 'qualityGates.manufacturingReview', label: 'Manufacturing Review' },
  { path: 'qualityGates.clientApproval', label: 'Client Approval' },
  { path: 'qualityGates.prototypeValidation', label: 'Prototype Validation' },
];
