/**
 * useProjectDeliverables Hook
 * Fetches deliverables from the unified `projectFiles` collection.
 * Single subscription replaces N per-item subcollection listeners.
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import {
  collection,
  query,
  where,
  limit,
  onSnapshot,
} from 'firebase/firestore';
import { db } from '@/shared/services/firebase';
import type { DesignItem, Deliverable } from '../types';
import type { ManagedFile } from '@/shared/services/fileManager';

export interface UseProjectDeliverablesReturn {
  /** Map of itemId -> Deliverable[] */
  deliverablesByItem: Map<string, Deliverable[]>;
  loading: boolean;
  error: Error | null;
  refresh: () => void;
}

/**
 * Map a ManagedFile from projectFiles into the Deliverable shape
 * expected by ProjectDeliverablesMatrix and other consumers.
 */
function toDeliverable(file: ManagedFile): Deliverable {
  const inferredType =
    file.deliverableType
    || (file.category === 'cad-model' ? '3d-model' : 'other');

  return {
    id: file.id,
    stage: 'concept' as any, // not tracked in projectFiles — matrix doesn't use this
    type: inferredType as any,
    name: file.name,
    description: '',
    storageUrl: file.storageUrl,
    storagePath: file.storagePath,
    googleDriveUrl: null,
    fileType: file.mimeType || '',
    fileSize: file.fileSize,
    mimeType: file.mimeType || undefined,
    fileName: file.fileName,
    version: file.version,
    previousVersionId: file.previousVersionId || null,
    status: file.status || 'draft',
    sharedToPortal: file.sharedToPortal || false,
    uploadedAt: file.uploadedAt,
    uploadedBy: file.uploadedBy,
    approvedAt: null,
    approvedBy: null,
    coversTypes: (file.coversTypes || []) as any[],
    isAutoGenerated: file.isAutoGenerated || false,
    autoGenSource: file.autoGenSource as any,
  };
}

export function useProjectDeliverables(
  projectId: string | null | undefined,
  _items: DesignItem[] // kept for API compat; not used for subscriptions anymore
): UseProjectDeliverablesReturn {
  const [deliverablesByItem, setDeliverablesByItem] = useState<Map<string, Deliverable[]>>(new Map());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const unsubRef = useRef<(() => void) | null>(null);

  const subscribe = useCallback((pid: string) => {
    // Tear down previous
    if (unsubRef.current) {
      unsubRef.current();
      unsubRef.current = null;
    }

    if (!pid) {
      setDeliverablesByItem(new Map());
      setLoading(false);
      return;
    }

    setLoading(true);

    // Single query: all latest deliverable files for this project
    const q = query(
      collection(db, 'projectFiles'),
      where('projectId', '==', pid),
      where('isLatest', '==', true),
      where('category', 'in', ['deliverable', 'production-doc', 'cad-model']),
      limit(500)
    );

    unsubRef.current = onSnapshot(
      q,
      (snapshot) => {
        const byItem = new Map<string, Deliverable[]>();

        for (const docSnap of snapshot.docs) {
          const file = { id: docSnap.id, ...docSnap.data() } as ManagedFile;
          if (!file.itemId) continue; // project-level files don't map to matrix rows

          const deliverable = toDeliverable(file);
          const list = byItem.get(file.itemId) || [];
          list.push(deliverable);
          byItem.set(file.itemId, list);
        }

        setDeliverablesByItem(byItem);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error('[useProjectDeliverables] Error:', err);
        setError(err instanceof Error ? err : new Error('Failed to fetch deliverables'));
        setLoading(false);
      }
    );
  }, []);

  useEffect(() => {
    if (projectId) {
      subscribe(projectId);
    } else {
      setDeliverablesByItem(new Map());
      setLoading(false);
    }

    return () => {
      if (unsubRef.current) {
        unsubRef.current();
        unsubRef.current = null;
      }
    };
  }, [projectId, subscribe]);

  const refresh = useCallback(() => {
    if (projectId) subscribe(projectId);
  }, [projectId, subscribe]);

  return { deliverablesByItem, loading, error, refresh };
}
