/**
 * Unified File Manager Service
 * CRUD, versioning, bulk operations, ZIP download
 * Uses top-level `projectFiles` Firestore collection
 */

import {
  collection,
  doc,
  addDoc,
  updateDoc,
  deleteDoc,
  getDocs,
  getDoc,
  query,
  where,
  limit,
  onSnapshot,
  serverTimestamp,
  writeBatch,
  type Timestamp,
} from 'firebase/firestore';
import {
  ref,
  uploadBytesResumable,
  getDownloadURL,
  deleteObject,
} from 'firebase/storage';
import { db } from '@/shared/services/firebase/firestore';
import { storage } from '@/shared/services/firebase';
import type {
  ManagedFile,
  FileUploadContext,
  FileQueryFilters,
  FileUploadProgress,
  FileCategory,
} from './types';
import { FILE_SIZE_LIMITS } from './types';

const FILES_COLLECTION = 'projectFiles';

// ============================================
// Upload
// ============================================

/**
 * Upload a file and create Firestore metadata doc
 */
export function uploadManagedFile(
  file: File,
  context: FileUploadContext,
  onProgress?: (progress: FileUploadProgress) => void
): { promise: Promise<ManagedFile>; abort: () => void } {
  // Naming Policy v4 — mandatory naming enforcement.
  //
  // When both `projectCode` and `policyName` are supplied, the storage
  // basename is the policy-compliant name so every download URL, bulk-ZIP
  // entry, and cross-system reference agrees with the display `name`.
  // When a policy name can't be constructed (no projectCode at callsite),
  // we fall back to the raw filename and log a warning — caller-driven
  // rejection is deferred to Phase 2 once every caller threads projectCode.
  if (!context.projectCode) {
    // eslint-disable-next-line no-console -- intentional until Phase 2 tightens this to a reject
    console.warn(
      `[uploadManagedFile] Upload of "${file.name}" missing projectCode — Naming Policy v4 cannot be enforced. ` +
        `Caller: module=${context.module} category=${context.category}`,
    );
  }
  const basenameSource = context.policyName || file.name;
  const sanitized = basenameSource.replace(/[^a-zA-Z0-9.-]/g, '_').substring(0, 150);
  // Timestamp + short random suffix prevents collisions when two users upload
  // the same filename within the same millisecond (possible during bulk imports
  // or parallel Workshop Viewer print-package pushes).
  const randomSuffix = Math.random().toString(36).slice(2, 8);
  const timestamp = Date.now();
  const storagePath = `project-files/${context.projectId}/${context.category}/${timestamp}_${randomSuffix}_${sanitized}`;
  const storageRef = ref(storage, storagePath);

  const uploadTask = uploadBytesResumable(storageRef, file, {
    contentType: file.type,
    customMetadata: {
      projectId: context.projectId,
      category: context.category,
      module: context.module,
      ...(context.itemId ? { itemId: context.itemId } : {}),
    },
  });

  const promise = new Promise<ManagedFile>((resolve, reject) => {
    uploadTask.on(
      'state_changed',
      (snapshot) => {
        onProgress?.({
          bytesTransferred: snapshot.bytesTransferred,
          totalBytes: snapshot.totalBytes,
          percentage: (snapshot.bytesTransferred / snapshot.totalBytes) * 100,
          state: snapshot.state as FileUploadProgress['state'],
        });
      },
      (error) => reject(error),
      async () => {
        try {
          const storageUrl = await getDownloadURL(uploadTask.snapshot.ref);
          const normalizedDeliverableType =
            context.deliverableType
            || (context.category === 'cad-model' ? '3d-model' : null);

          const fileDoc = {
            name: context.policyName || (normalizedDeliverableType
              ? `${normalizedDeliverableType} - ${file.name}`
              : file.name),
            fileName: file.name,
            fileSize: file.size,
            mimeType: file.type || 'application/octet-stream',
            storagePath,
            storageUrl,
            projectId: context.projectId,
            projectCode: context.projectCode || null,
            itemId: context.itemId || null,
            itemName: context.itemName || null,
            manufacturingOrderId: context.manufacturingOrderId || null,
            module: context.module,
            category: context.category,
            deliverableType: normalizedDeliverableType,
            version: 1,
            previousVersionId: null,
            isLatest: true,
            isAutoGenerated: context.isAutoGenerated || false,
            autoGenSource: context.autoGenSource || null,
            autoGenHash: context.autoGenHash || null,
            uploadedAt: serverTimestamp(),
            uploadedBy: context.uploadedBy || '',
            uploadedByName: context.uploadedByName || null,
            updatedAt: serverTimestamp(),
            tags: context.tags || [],
          };

          const docRef = await addDoc(collection(db, FILES_COLLECTION), fileDoc);
          const saved = await getDoc(docRef);

          // RAG auto-update hook removed in Phase 1.C (design-manager deleted).
          // TODO Phase 3: re-wire to `@/modules/campaigns/services/ragAutoUpdateService`
          // once Campaigns module is built — Campaign deliverable uploads should
          // similarly nudge RAG state.
          void normalizedDeliverableType;

          resolve({
            id: docRef.id,
            ...fileDoc,
            uploadedAt: saved.data()?.uploadedAt || ({} as Timestamp),
            updatedAt: saved.data()?.updatedAt || ({} as Timestamp),
          } as unknown as ManagedFile);
        } catch (error) {
          reject(error);
        }
      }
    );
  });

  return {
    promise,
    abort: () => uploadTask.cancel(),
  };
}

// ============================================
// Replace (versioning)
// ============================================

/**
 * Replace a file with a new version.
 * - Manual files: archives old version, creates new doc with version+1
 * - Auto-generated files: overwrites in place
 *
 * Approval lock (F-E2): rejects when the existing file is marked `approved`
 * unless `allowApprovedOverride` is explicitly true. The Firestore rules
 * mirror this gate for admin-only override — pass `allowApprovedOverride`
 * only after the caller has obtained admin confirmation from the UI.
 */
export async function replaceFile(
  existingFileId: string,
  newFile: File,
  uploadedBy: string,
  uploadedByName?: string,
  allowApprovedOverride = false,
): Promise<ManagedFile> {
  const existingDoc = await getDoc(doc(db, FILES_COLLECTION, existingFileId));
  if (!existingDoc.exists()) throw new Error('File not found');

  const existing = { id: existingDoc.id, ...existingDoc.data() } as ManagedFile;

  if (existing.status === 'approved' && !allowApprovedOverride) {
    throw new Error(
      `File "${existing.name}" is marked approved. Mark it for review first, or request admin override before replacing.`,
    );
  }

  if (existing.isAutoGenerated) {
    // Auto-gen: delete old storage, upload new in same path
    try { await deleteObject(ref(storage, existing.storagePath)); } catch { /* ok */ }

    const storageRef = ref(storage, existing.storagePath);
    const uploadTask = uploadBytesResumable(storageRef, newFile, {
      contentType: newFile.type,
    });
    await uploadTask;
    const newUrl = await getDownloadURL(storageRef);

    await updateDoc(doc(db, FILES_COLLECTION, existingFileId), {
      storageUrl: newUrl,
      fileSize: newFile.size,
      mimeType: newFile.type,
      fileName: newFile.name,
      updatedAt: serverTimestamp(),
      uploadedBy,
      uploadedByName: uploadedByName || null,
    });

    return { ...existing, storageUrl: newUrl, fileSize: newFile.size, fileName: newFile.name };
  }

  // Manual file: archive old, create new version.
  //
  // Atomicity: upload storage first (side-effectful but recoverable on retry),
  // then atomically flip `isLatest` on the old doc and create the new doc in a
  // single `writeBatch`. If the Storage upload fails, the previous version
  // remains the latest — no inconsistent state. If the batch fails, we clean
  // up the orphaned Storage object so repeat attempts don't accumulate junk.
  //
  // Storage basename reuses the existing file's policy-compliant display
  // `name` so every version in the chain presents consistently.
  const timestamp = Date.now();
  const randomSuffix = Math.random().toString(36).slice(2, 8);
  const basenameSource = existing.name || newFile.name;
  const sanitized = basenameSource.replace(/[^a-zA-Z0-9.-]/g, '_').substring(0, 150);
  const storagePath = `project-files/${existing.projectId}/${existing.category}/${timestamp}_${randomSuffix}_${sanitized}`;
  const storageRef = ref(storage, storagePath);

  const uploadTask = uploadBytesResumable(storageRef, newFile, {
    contentType: newFile.type,
  });
  await uploadTask;
  const storageUrl = await getDownloadURL(storageRef);

  const newVersion = existing.version + 1;
  const newDocRef = doc(collection(db, FILES_COLLECTION));
  const newDoc = {
    name: existing.name,
    fileName: newFile.name,
    fileSize: newFile.size,
    mimeType: newFile.type || 'application/octet-stream',
    storagePath,
    storageUrl,
    projectId: existing.projectId,
    projectCode: existing.projectCode || null,
    itemId: existing.itemId || null,
    itemName: existing.itemName || null,
    manufacturingOrderId: existing.manufacturingOrderId || null,
    module: existing.module,
    category: existing.category,
    deliverableType: existing.deliverableType || null,
    version: newVersion,
    previousVersionId: existingFileId,
    isLatest: true,
    isAutoGenerated: false,
    autoGenSource: null,
    autoGenHash: null,
    uploadedAt: serverTimestamp(),
    uploadedBy,
    uploadedByName: uploadedByName || null,
    updatedAt: serverTimestamp(),
    tags: existing.tags || [],
  };

  try {
    const batch = writeBatch(db);
    batch.update(doc(db, FILES_COLLECTION, existingFileId), {
      isLatest: false,
      updatedAt: serverTimestamp(),
    });
    batch.set(newDocRef, newDoc);
    await batch.commit();
  } catch (err) {
    // Firestore commit failed — roll back the orphaned Storage upload so a
    // retry starts clean and we don't leak storage objects with no metadata.
    try { await deleteObject(storageRef); } catch { /* best effort */ }
    throw err;
  }

  const saved = await getDoc(newDocRef);

  return {
    id: newDocRef.id,
    ...newDoc,
    uploadedAt: saved.data()?.uploadedAt || ({} as Timestamp),
    updatedAt: saved.data()?.updatedAt || ({} as Timestamp),
  } as unknown as ManagedFile;
}

// ============================================
// Overwrite (destructive — same version, same document)
// ============================================

/**
 * Overwrite a file in place without creating a new version.
 *
 * Order of operations (upload-before-delete so a failed upload never destroys
 * the original):
 *   1. Upload new file to a fresh storage path.
 *   2. Update the Firestore doc to point at the new path.
 *   3. Delete the old storage object.
 *
 * If step 2 fails, we roll back the newly-uploaded storage object so the doc
 * still points at the original (which has NOT been deleted).
 */
export async function overwriteFile(
  existingFileId: string,
  newFile: File,
  newName?: string,
  uploadedBy?: string,
  uploadedByName?: string,
  allowApprovedOverride = false,
): Promise<ManagedFile> {
  const existingDoc = await getDoc(doc(db, FILES_COLLECTION, existingFileId));
  if (!existingDoc.exists()) throw new Error('File not found');

  const existing = { id: existingDoc.id, ...existingDoc.data() } as ManagedFile;
  const previousStoragePath = existing.storagePath;

  // Approval lock — see replaceFile docstring.
  if (existing.status === 'approved' && !allowApprovedOverride) {
    throw new Error(
      `File "${existing.name}" is marked approved. Mark it for review first, or request admin override before overwriting.`,
    );
  }

  // 1. Upload new file to fresh path FIRST.
  const timestamp = Date.now();
  const randomSuffix = Math.random().toString(36).slice(2, 8);
  const basenameSource = newName || existing.name || newFile.name;
  const sanitized = basenameSource.replace(/[^a-zA-Z0-9.-]/g, '_').substring(0, 150);
  const storagePath = `project-files/${existing.projectId}/${existing.category}/${timestamp}_${randomSuffix}_${sanitized}`;
  const storageRef = ref(storage, storagePath);

  const uploadTask = uploadBytesResumable(storageRef, newFile, {
    contentType: newFile.type,
  });
  await uploadTask;
  const storageUrl = await getDownloadURL(storageRef);

  const updates: Record<string, unknown> = {
    fileName: newFile.name,
    fileSize: newFile.size,
    mimeType: newFile.type || 'application/octet-stream',
    storagePath,
    storageUrl,
    updatedAt: serverTimestamp(),
  };
  if (newName) updates.name = newName;
  if (uploadedBy) updates.uploadedBy = uploadedBy;
  if (uploadedByName !== undefined) updates.uploadedByName = uploadedByName || null;

  // 2. Update the doc to point at the new storage object.
  try {
    await updateDoc(doc(db, FILES_COLLECTION, existingFileId), updates);
  } catch (err) {
    // Roll back the orphaned new upload — the original is still referenced by
    // the unchanged Firestore doc, so the file is intact.
    try { await deleteObject(storageRef); } catch { /* best effort */ }
    throw err;
  }

  // 3. Now that the doc points at the new path, delete the old storage object.
  //    A failure here is non-fatal — it just leaves an orphan, which a
  //    reconciliation job can sweep later.
  try { await deleteObject(ref(storage, previousStoragePath)); } catch { /* best effort */ }

  return {
    ...existing,
    ...updates,
    storageUrl,
    storagePath,
  } as ManagedFile;
}

// ============================================
// Delete
// ============================================

// ============================================
// Status & Portal Sharing
// ============================================

/** Update a file's approval status */
export async function updateFileStatus(
  fileId: string,
  status: 'draft' | 'review' | 'approved' | 'superseded',
  userId?: string
): Promise<void> {
  const updates: Record<string, unknown> = {
    status,
    updatedAt: serverTimestamp(),
  };
  if (status === 'approved' && userId) {
    updates.approvedBy = userId;
    updates.approvedAt = serverTimestamp();
  }
  await updateDoc(doc(db, FILES_COLLECTION, fileId), updates);
}

/** Toggle portal sharing for a file */
export async function togglePortalSharing(
  fileId: string,
  share: boolean,
  userId: string,
  portalDisplayName?: string
): Promise<void> {
  const updates: Record<string, unknown> = {
    sharedToPortal: share,
    updatedAt: serverTimestamp(),
  };
  if (share) {
    updates.sharedToPortalAt = serverTimestamp();
    updates.sharedToPortalBy = userId;
    if (portalDisplayName) updates.portalDisplayName = portalDisplayName;
  }
  await updateDoc(doc(db, FILES_COLLECTION, fileId), updates);
}

// ============================================
// Delete
// ============================================

/** Delete a single file (storage + Firestore + mirrored deliverable if any) */
export async function deleteManagedFile(fileId: string): Promise<void> {
  const fileDoc = await getDoc(doc(db, FILES_COLLECTION, fileId));
  if (!fileDoc.exists()) return;

  const data = fileDoc.data() as ManagedFile & {
    _sourceId?: string;
    _sourceCollection?: string;
  };

  try {
    await deleteObject(ref(storage, data.storagePath));
  } catch {
    // Storage file may already be gone
  }

  // If this was mirrored from a deliverable, also delete the source deliverable
  if (data._sourceId && data._sourceCollection === 'deliverables' && data.projectId && data.itemId) {
    try {
      await deleteDoc(
        doc(db, 'designProjects', data.projectId, 'designItems', data.itemId, 'deliverables', data._sourceId)
      );
    } catch {
      // Source deliverable may already be gone
    }
  }

  await deleteDoc(doc(db, FILES_COLLECTION, fileId));
}

/** Bulk delete files */
export async function deleteManagedFiles(fileIds: string[]): Promise<{ deleted: number; failed: number }> {
  let deleted = 0;
  let failed = 0;
  for (const id of fileIds) {
    try {
      await deleteManagedFile(id);
      deleted++;
    } catch {
      failed++;
    }
  }
  return { deleted, failed };
}

// ============================================
// Query
// ============================================

/** Hard ceiling on how many latest files the subscription fetches in one shot. */
export const PROJECT_FILES_SUBSCRIPTION_CAP = 500;

/**
 * Subscription payload — files plus a truncation signal so the UI can warn
 * when a project has more latest files than we're willing to stream at once.
 */
export interface ProjectFilesSnapshot {
  files: ManagedFile[];
  /**
   * True when the server returned exactly `PROJECT_FILES_SUBSCRIPTION_CAP`
   * documents — there may be more that we are not showing. Mature projects
   * should switch to cursor pagination (Phase 2).
   */
  truncated: boolean;
}

/**
 * Subscribe to real-time file updates for a project.
 * Calls callback immediately with current data and on every change.
 * Returns an unsubscribe function.
 *
 * Emits {@link ProjectFilesSnapshot} (files + truncation signal) so the UI
 * can render a "showing 500 of N+ — some files hidden" warning when the cap
 * is hit rather than silently dropping the tail.
 */
export function subscribeToProjectFiles(
  projectId: string,
  filters: FileQueryFilters | undefined,
  callback: (snap: ProjectFilesSnapshot) => void,
): () => void {
  // Keep query constraints minimal to use the projectId+isLatest index (already built).
  // itemId/category filtering is done client-side to avoid requiring extra composite indexes
  // while they are still building after migration.
  const q = query(
    collection(db, FILES_COLLECTION),
    where('projectId', '==', projectId),
    where('isLatest', '==', true),
    limit(PROJECT_FILES_SUBSCRIPTION_CAP),
  );

  return onSnapshot(
    q,
    (snapshot) => {
      let files = snapshot.docs.map((d) => ({ id: d.id, ...d.data() } as ManagedFile));
      const truncated = snapshot.size >= PROJECT_FILES_SUBSCRIPTION_CAP;

      // Client-side filtering
      if (filters?.itemId) files = files.filter((f) => f.itemId === filters.itemId);
      if (filters?.category) files = files.filter((f) => f.category === filters.category);

      // Sort newest first
      files.sort((a, b) => (b.uploadedAt?.toMillis?.() || 0) - (a.uploadedAt?.toMillis?.() || 0));

      callback({ files, truncated });
    },
    (err) => {
      console.error('[subscribeToProjectFiles] Error:', err);
      callback({ files: [], truncated: false });
    },
  );
}

/** Get all latest files for a project, with optional filters */
export async function getProjectFiles(
  projectId: string,
  filters?: FileQueryFilters
): Promise<ManagedFile[]> {
  const constraints = [
    where('projectId', '==', projectId),
  ];

  // Default to latest only unless explicitly overridden
  if (filters?.isLatest !== false) {
    constraints.push(where('isLatest', '==', true));
  }

  if (filters?.category) {
    constraints.push(where('category', '==', filters.category));
  }
  if (filters?.module) {
    constraints.push(where('module', '==', filters.module));
  }
  if (filters?.itemId) {
    constraints.push(where('itemId', '==', filters.itemId));
  }
  if (filters?.isAutoGenerated !== undefined) {
    constraints.push(where('isAutoGenerated', '==', filters.isAutoGenerated));
  }

  const q = query(collection(db, FILES_COLLECTION), ...constraints);
  const snapshot = await getDocs(q);

  return snapshot.docs
    .map((d) => ({ id: d.id, ...d.data() } as ManagedFile))
    .sort((a, b) => {
      const aTime = a.uploadedAt?.toMillis?.() || 0;
      const bTime = b.uploadedAt?.toMillis?.() || 0;
      return bTime - aTime;
    });
}

/** Get version history for a file (walk previousVersionId chain) */
export async function getFileVersions(fileId: string): Promise<ManagedFile[]> {
  const versions: ManagedFile[] = [];

  // First get the latest version in this chain
  const startDoc = await getDoc(doc(db, FILES_COLLECTION, fileId));
  if (!startDoc.exists()) return [];

  const startFile = { id: startDoc.id, ...startDoc.data() } as ManagedFile;
  versions.push(startFile);

  // Walk backwards through previousVersionId
  let currentId = startFile.previousVersionId;
  while (currentId) {
    const prevDoc = await getDoc(doc(db, FILES_COLLECTION, currentId));
    if (!prevDoc.exists()) break;
    const prevFile = { id: prevDoc.id, ...prevDoc.data() } as ManagedFile;
    versions.push(prevFile);
    currentId = prevFile.previousVersionId;
  }

  // Also find any newer versions that point to this file
  const newerQ = query(
    collection(db, FILES_COLLECTION),
    where('previousVersionId', '==', fileId)
  );
  const newerSnap = await getDocs(newerQ);
  for (const d of newerSnap.docs) {
    const f = { id: d.id, ...d.data() } as ManagedFile;
    if (!versions.find((v) => v.id === f.id)) {
      versions.push(f);
    }
  }

  // Sort by version descending
  return versions.sort((a, b) => b.version - a.version);
}

// ============================================
// ZIP Download
// ============================================

/**
 * Download multiple files as a ZIP archive.
 * Returns a report of how many succeeded / failed so the caller can surface
 * partial failure to the user (policy: bulk operations must never fail silently).
 */
export async function downloadFilesAsZip(
  files: ManagedFile[],
  zipName: string = 'project-files.zip'
): Promise<{ zipped: number; failed: string[] }> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  const failed: string[] = [];
  let zipped = 0;

  const fetchPromises = files.map(async (file) => {
    try {
      const response = await fetch(file.storageUrl);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const blob = await response.blob();
      // Prevent name collisions. Prefer the policy-compliant display name over
      // the raw storage basename so the ZIP contents match what users see in
      // the UI and what the Naming Policy v4 mandates.
      const folder = file.itemName || file.category;
      const entryName = file.name || file.fileName;
      zip.file(`${folder}/${entryName}`, blob);
      zipped++;
    } catch (err) {
      console.warn(`Failed to fetch file ${file.fileName}:`, err);
      failed.push(file.name || file.fileName);
    }
  });

  await Promise.all(fetchPromises);

  const content = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(content);
  const a = document.createElement('a');
  a.href = url;
  a.download = zipName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { zipped, failed };
}

// ============================================
// Validation
// ============================================

/** Validate a file before upload */
export function validateFile(
  file: File,
  category: FileCategory
): { valid: boolean; error?: string } {
  const maxSize = FILE_SIZE_LIMITS[category] || 100 * 1024 * 1024;
  if (file.size > maxSize) {
    const mb = Math.round(maxSize / (1024 * 1024));
    return { valid: false, error: `File exceeds ${mb}MB limit` };
  }
  return { valid: true };
}
