/**
 * Unified File Manager Types
 * Shared type definitions for cross-module file management
 */

import type { Timestamp } from 'firebase/firestore';

/** File categories across modules */
export type FileCategory =
  | 'deliverable'
  | 'client-document'
  | 'production-doc'
  | 'report'
  // P21.3 — unified CAD handling. Workshop Viewer uploads (3ds/dxf/obj/
  // fbx/glb/stl) go here, which lets the File Manager list them alongside
  // deliverables + offer "Open in Studio" on rows instead of hiding 3D
  // assets behind the bespoke `workshop-viewer/{ts}/` storage path.
  | 'cad-model';

/** Source module for the file */
export type FileModule = 'design-manager' | 'manufacturing' | 'shared';

/**
 * Managed file — single Firestore document in `projectFiles` collection
 */
export interface ManagedFile {
  id: string;
  name: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
  storagePath: string;
  storageUrl: string;

  // Context
  projectId: string;
  /**
   * Human-readable, policy-compliant project code — e.g. `DF-2025-001`.
   * Denormalised onto every file doc so Drive mirroring, naming enforcement,
   * and cross-system (Notion/Drive) joins can use the canonical policy key
   * instead of the opaque Firestore `projectId`. See Naming Policy v4.
   */
  projectCode?: string;
  itemId?: string;
  itemName?: string;
  manufacturingOrderId?: string;
  module: FileModule;
  category: FileCategory;
  deliverableType?: string; // e.g. 'cut-list', 'bom', 'shop-drawing'

  // Versioning
  version: number;
  previousVersionId?: string;
  isLatest: boolean;

  // Auto-generation
  isAutoGenerated: boolean;
  autoGenSource?: string;
  autoGenHash?: string;

  // Approval / status
  status?: 'draft' | 'review' | 'approved' | 'superseded';
  coversTypes?: string[];          // multi-type coverage (e.g. one drawing satisfies shop-drawing + spec)

  // Portal sharing
  sharedToPortal?: boolean;
  sharedToPortalAt?: Timestamp;
  sharedToPortalBy?: string;
  portalDisplayName?: string;

  // Drive mirror (Phase 2 — Shared Drive Architecture v3 §01_Active-Projects/{01..07})
  /** Google Drive file ID of the mirrored copy. Null until the mirror trigger writes it. */
  driveFileId?: string | null;
  /** `webViewLink` from the Drive API — "Open in Drive" anchor target. */
  driveWebViewLink?: string | null;
  /** Which `01..07` subfolder under the project folder this file was routed to. */
  driveFolderSubpath?: string | null;
  /** Server timestamp of the successful mirror write. */
  driveSyncedAt?: Timestamp | null;
  /** Last error from the mirror CF, if any. Cleared on next successful sync. */
  driveSyncError?: string | null;

  // Archive lifecycle (Phase 4 — Shared Drive Architecture v3 §02_Archive/{Year})
  /**
   * True when the parent project has been archived. Flipped by the
   * `archiveProject` Cloud Function; UI hides archived files by default
   * and surfaces them behind an explicit "show archived" toggle.
   */
  archived?: boolean;
  /** Server timestamp set by the archive CF on successful flag-write. */
  archivedAt?: Timestamp | null;
  /** Auth UID (or `system` for the scheduled sweep) that archived it. */
  archivedBy?: string | null;

  // Metadata
  uploadedAt: Timestamp;
  uploadedBy: string;
  uploadedByName?: string;
  updatedAt: Timestamp;
  tags?: string[];
}

/**
 * Context required when uploading a new file
 */
export interface FileUploadContext {
  projectId: string;
  /** Policy-compliant project code (e.g. `DF-2025-001`). See {@link ManagedFile.projectCode}. */
  projectCode?: string;
  itemId?: string;
  itemName?: string;
  manufacturingOrderId?: string;
  module: FileModule;
  category: FileCategory;
  deliverableType?: string;
  /** Policy-compliant display name (overrides default name generation) */
  policyName?: string;
  /** Uploader's auth UID — persisted to the ManagedFile doc and checked by Firestore rules on update/delete */
  uploadedBy?: string;
  /** Uploader's display name — persisted to the ManagedFile doc for UI */
  uploadedByName?: string;
  tags?: string[];
  // Auto-gen fields
  isAutoGenerated?: boolean;
  autoGenSource?: string;
  autoGenHash?: string;
}

/**
 * Filters for querying files
 */
export interface FileQueryFilters {
  category?: FileCategory;
  module?: FileModule;
  itemId?: string;
  isAutoGenerated?: boolean;
  tags?: string[];
  isLatest?: boolean;
}

/**
 * Upload progress tracking
 */
export interface FileUploadProgress {
  bytesTransferred: number;
  totalBytes: number;
  percentage: number;
  state: 'running' | 'paused' | 'success' | 'canceled' | 'error';
}

/** File size limits by category (bytes) */
export const FILE_SIZE_LIMITS: Record<FileCategory, number> = {
  'deliverable': 100 * 1024 * 1024,      // 100MB
  'client-document': 50 * 1024 * 1024,    // 50MB
  'production-doc': 100 * 1024 * 1024,    // 100MB
  'report': 50 * 1024 * 1024,            // 50MB
  // 3DS/DXF export files can easily run 200MB+ for fitout-scale scenes,
  // and PolyBoard users occasionally ship 400MB blobs. Keep generous.
  'cad-model': 500 * 1024 * 1024,        // 500MB
};

/** Category display names */
export const CATEGORY_LABELS: Record<FileCategory, string> = {
  'deliverable': 'Deliverables',
  'client-document': 'Client Documents',
  'production-doc': 'Production Documents',
  'report': 'Reports',
  'cad-model': 'CAD Models',
};

/**
 * Extensions the Workshop Viewer can open. Source of truth for
 * - extension-based category classification ({@link getCategoryFromFileName}),
 * - the File Manager's "Process in Workshop" row action predicate,
 * - the Workshop Viewer's file-type accept filters.
 *
 * Keep this list in sync with the model parser's supported formats
 * (`src/subsidiaries/finishes/design-studio/services/modelParser`).
 */
export const CAD_MODEL_EXTENSIONS: ReadonlyArray<string> = [
  '3ds', 'dxf', 'obj', 'fbx', 'glb', 'gltf', 'stl',
];

/** Case-insensitive test for "is this filename a CAD model file?" */
export function isCadModelFileName(fileName: string | null | undefined): boolean {
  if (!fileName) return false;
  const ext = fileName.split('.').pop()?.toLowerCase();
  return !!ext && CAD_MODEL_EXTENSIONS.includes(ext);
}

/**
 * Best-guess {@link FileCategory} from a filename. Returns `null` when
 * the file doesn't clearly belong to a category — callers decide the
 * default (usually `'deliverable'`) in that case. This is intentionally
 * narrow: it only fires on extensions we have strong opinions about
 * (CAD models), so it doesn't accidentally re-route a PDF spec sheet
 * that happened to be named `something.pdf.obj.pdf`.
 */
export function getCategoryFromFileName(
  fileName: string | null | undefined,
): FileCategory | null {
  if (isCadModelFileName(fileName)) return 'cad-model';
  return null;
}

/** Format file size for display */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

/**
 * Get file icon type.
 *
 * Prefer the filename when available because CAD formats (.3ds, .dxf,
 * .obj, .fbx) ship with `application/octet-stream` on most browsers —
 * the old MIME-only check was returning 'model' for every arbitrary
 * binary blob, which is both over- and under-inclusive.
 */
export function getFileIconType(
  mimeType: string | null | undefined,
  fileName?: string | null,
): 'image' | 'pdf' | 'spreadsheet' | 'model' | 'document' | 'other' {
  // Filename-based CAD detection wins over MIME because browsers lie.
  if (fileName && isCadModelFileName(fileName)) return 'model';

  if (!mimeType) return 'other';
  if (mimeType.startsWith('image/')) return 'image';
  if (mimeType === 'application/pdf') return 'pdf';
  if (mimeType.includes('spreadsheet') || mimeType === 'text/csv') return 'spreadsheet';
  if (mimeType.includes('model')) return 'model';
  if (mimeType.includes('document') || mimeType.includes('word')) return 'document';
  return 'other';
}
